### ISSUE TITLE
Segmentation fault for gcp-cups-connector on Raspbian 

### ISSUE THREAD

**Issue by ngulden** [google/cups-connector#100]
I try to install gcp-cups-connector on Raspbian with Debian Jessie. 
```
$ uname -a
Linux raspberrypi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux
```

I followed your wiki instructions. The config file is created successfully. But running gcp-cups-connector comes up with the following:
```
$ /gcp-cups-connector
E1001 22:39:33.487409    2725 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version 2015.09.30-linux
Google Cloud Print CUPS Connector version 2015.09.30-linux
Segmentation fault
```

I then compile Go 1.4 and Go 1.5.1 as suggested and tried again. Same error. The logfiles don't give any further information. 

I also tried to build gcp-cups-connector from source:
```
$ go get github.com/google/cups-connector/2015.09.30
package github.com/google/cups-connector/2015.09.30: cannot find package "github.com/google/cups-connector/2015.09.30" in any of:
        /home/pi/go1.5/src/github.com/google/cups-connector/2015.09.30 (from $GOROOT)
        /home/pi/go/src/github.com/google/cups-connector/2015.09.30 (from $GOPATH)

$ go get github.com/google/cups-connector/
can't load package: package github.com/google/cups-connector: no buildable Go source files in /home/pi/go1.5/src/github.com/google/cups-connector
```

Can you provide a hint what I could do or let me know, what else you need to know to hunt down that segmentation fault.

**Comment by jacobmarble** [comment]
I don't know what's happening. Give me some time to find a RPi running Jessie; it's not happening on Wheezy.

Please paste the output of `ldd gcp-cups-connector`.

**Comment by jacobmarble** [comment]
OK, I found one, and confirmed the problem. Still don't know why it happens, though.

**Comment by jay0lee** [comment]
Try running:

go get github.com/google/cups-connector/...

(that's 3 dots at the end) in order to compile gcp-cups-connector for yourself.

**Comment by ngulden** [comment]
@jay0lee : I tried it with the three dots, as well. It didn't work either. gcp-cups-connector was not compiled. I think I forgot them in my last console output in my initial posting. 

I'm not that familiar with go and I couldn't find any other hint than the wiki on how to compile gcp-cups-connector. I expected makefiles or other documentation in the src archive distribution.

**Comment by jay0lee** [comment]
@ngulden what error exactly is returned with:

go get github.com/google/cups-connector/...

**Comment by jacobmarble** [comment]
@ngulden ping

**Comment by ngulden** [comment]
Sorry for the delay.

@jay0lee : The command does not return anything.
```
$ go version
go version go1.5.1 linux/arm
$ go get github.com/google/cups-connector/...
$
$ echo $?
0
```

@jacobmarble 
```
$ ldd gcp-cups-connector | sort
        libavahi-client.so.3 => /usr/lib/arm-linux-gnueabihf/libavahi-client.so.3 (0xb6e50000)
        libavahi-common.so.3 => /usr/lib/arm-linux-gnueabihf/libavahi-common.so.3 (0xb6e35000)
        libcom_err.so.2 => /lib/arm-linux-gnueabihf/libcom_err.so.2 (0xb6805000)
        libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0xb6cc8000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6b63000)
        libcups.so.2 => /usr/lib/arm-linux-gnueabihf/libcups.so.2 (0xb6e6f000)
        libdbus-1.so.3 => /lib/arm-linux-gnueabihf/libdbus-1.so.3 (0xb691e000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb690b000)
        libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0xb665f000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6631000)
        libgmp.so.10 => /usr/lib/arm-linux-gnueabihf/libgmp.so.10 (0xb666f000)
        libgnutls-deb0.so.28 => /usr/lib/arm-linux-gnueabihf/libgnutls-deb0.so.28 (0xb6a0d000)
        libgssapi_krb5.so.2 => /usr/lib/arm-linux-gnueabihf/libgssapi_krb5.so.2 (0xb6b1a000)
        libhogweed.so.2 => /usr/lib/arm-linux-gnueabihf/libhogweed.so.2 (0xb66e1000)
        libk5crypto.so.3 => /usr/lib/arm-linux-gnueabihf/libk5crypto.so.3 (0xb6819000)
        libkeyutils.so.1 => /lib/arm-linux-gnueabihf/libkeyutils.so.1 (0xb67e1000)
        libkrb5.so.3 => /usr/lib/arm-linux-gnueabihf/libkrb5.so.3 (0xb6857000)
        libkrb5support.so.0 => /usr/lib/arm-linux-gnueabihf/libkrb5support.so.0 (0xb67ec000)
        /lib/ld-linux-armhf.so.3 (0xb6f0c000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb696a000)
        libnettle.so.4 => /usr/lib/arm-linux-gnueabihf/libnettle.so.4 (0xb671a000)
        libp11-kit.so.0 => /usr/lib/arm-linux-gnueabihf/libp11-kit.so.0 (0xb677b000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6ca0000)
        libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb67bc000)
        libtasn1.so.6 => /usr/lib/arm-linux-gnueabihf/libtasn1.so.6 (0xb675a000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb69e6000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0xb6ef4000)
```

**Comment by PortableTech** [comment]
Hey all, tried this last night on my Raspberry Pi 2 and am getting the same result on the latest Raspbian release.

**Comment by ngulden** [comment]
My first try with release 2015.09.22 caused a segmentation fault, as well.

**Comment by jacobmarble** [comment]
I'll create a new release tomorrow with binaries for both wheezy and jessie.

**Comment by jacobmarble** [comment]
@PortableTech are you running jessie on your RPi2?

**Comment by jacobmarble** [comment]
Oh, looks like Raspbian jessie is official now.
https://www.raspberrypi.org/blog/raspbian-jessie-is-here/

**Comment by PortableTech** [comment]
Yes, you are correct.

**Comment by jacobmarble** [comment]
OK, give the latest release a shot. I don't have a RPi2 to test with, but I do have both Raspbian wheezy and jessie build scripts now.

**Comment by ngulden** [comment]
I just downloaded an installed the build from 29cea39 on my RPI 1 with Raspbian Jessie and the segmentation fault is gone. My printer shows up in the printers view on my Android as expected. Thanks.

**Comment by jds13** [comment]
Thank you very much!
