### ISSUE TITLE
Failed to register printer, illegal description of cloud-unit

### ISSUE THREAD

**Issue by holckj** [google/cups-connector#101]
I managed to compile and install gcp-bus-connector, but get this message, when I try to run it:

E1002 17:56:23.723641   22064 printermanager.go:227] Failed to register printer MC560: https://www.google.com/cloudprint/register call failed: Ugyldig beskrivelse af skyenhed.

The last part of the message is in Danish - translated to English it reads something like "Illegal description of cloud-unit"

**Comment by jacobmarble** [comment]
Please email your PPD to me. It should be in /etc/cups/ppd.

What operating system are you using? Did you use the binaries or build from source?

**Comment by holckj** [comment]
Thanks for your quick reply. I've attached my ppd-file from cups. I run
sme-server (contribs.org), a Centos 6 variant. I built from source (and
struggled quite a bit with errors from Python regarding the number of
arguments to readline...)

I'll of course be happy to provide any further information.

**Comment by jacobmarble** [comment]
CentOS 6 is packaged with CUPS 1.4, which I've never tested. What version of CUPS does your SME install have?

**Comment by jacobmarble** [comment]
Looks like GitHub doesn't do attachments via email, but you can attach in the web interface.
https://github.com/google/cups-connector/issues/101

**Comment by holckj** [comment]
cups-libs-1.4.2-72.el6.x86_64
cups-devel-1.4.2-72.el6.x86_64
cups-1.4.2-72.el6.x86_64

**Comment by holckj** [comment]
The web interface didn't allow me to attach a ppd-file. You can get it here:
http://ibsgaarden.dk/MC560.ppd

**Comment by jacobmarble** [comment]
Alright

**Comment by jacobmarble** [comment]
Got it. Please verify MD5 checksum
a52e6dd496de16bab30b27fbccd99d98

**Comment by holckj** [comment]
openssl dgst -md5 MC560.ppd
MD5(MC560.ppd)= a52e6dd496de16bab30b27fbccd99d98

**Comment by jacobmarble** [comment]
Great. I'm not seeing any problem with this PPD from Ubuntu 14.04. Please send the output from this Python script:
```python
import cups
import sys

c = cups.Connection()
attributes = c.getPrinterAttributes(sys.argv[1])
for key in sorted(attributes):
  print key, attributes[key]
```

Take a good look at the output before posting it publicly. Feel free to email it to me at jacobmarble@google.com

**Comment by jacobmarble** [comment]
Sorry, run it like this:
```sh
$ python script.py printername
```

**Comment by holckj** [comment]
I'm not much of a Python guru, unfortunately ... got this, after installing
system.config-printer-libs:

$ python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    attributes = c.getPrinterAttributes(sys.argv[1])IndexError: list
index out of range

**Comment by holckj** [comment]
$ python test.py MC560
auth-info-required none
charset-configured utf-8
charset-supported [u'us-ascii', u'utf-8']
color-supported True
compression-supported [u'none', u'gzip']
copies-default 1
copies-supported (1, 9999)
cups-version 1.4.2
device-uri socket://192.168.10.11
document-format-default application/octet-stream
document-format-supported [u'application/octet-stream',
u'application/pdf', u'application/postscript',
u'application/vnd.cups-banner', u'application/vnd.cups-command',
u'application/vnd.cups-postscript', u'application/vnd.cups-raw',
u'application/vnd.hp-hpgl', u'application/x-cshell',
u'application/x-csource', u'application/x-perl',
u'application/x-shell', u'image/gif', u'image/jpeg', u'image/png',
u'image/tiff', u'image/x-bitmap', u'image/x-photocd',
u'image/x-portable-anymap', u'image/x-portable-bitmap',
u'image/x-portable-graymap', u'image/x-portable-pixmap',
u'image/x-sgi-rgb', u'image/x-sun-raster', u'image/x-xbitmap',
u'image/x-xpixmap', u'text/css', u'text/html', u'text/plain']
finishings-default 3
finishings-supported [3]
generated-natural-language-supported [u'en_US']
ipp-versions-supported [u'1.0', u'1.1', u'2.0', u'2.1']
job-hold-until-default no-hold
job-hold-until-supported [u'no-hold', u'indefinite', u'day-time',
u'evening', u'night', u'second-shift', u'third-shift', u'weekend']
job-k-limit 0
job-page-limit 0
job-priority-default 50
job-priority-supported [100]
job-quota-period 0
job-settable-attributes-supported [u'copies', u'finishings',
u'job-hold-until', u'job-priority', u'media',
u'multiple-document-handling', u'number-up', u'orientation-requested',
u'page-ranges', u'print-quality', u'printer-resolution', u'sides']
job-sheets-default (u'none', u'none')
job-sheets-supported [u'none', u'classified', u'confidential', u'mls',
u'secret', u'selinux', u'standard', u'te', u'topsecret',
u'unclassified']
marker-change-time 1443808170
marker-colors [u'#000000', u'#00FFFF', u'#FF00FF', u'#FFFF00',
u'#000000', u'#00FFFF', u'#FF00FF', u'#FFFF00', u'none', u'none',
u'none']
marker-levels [100, 10, 10, 60, 28, 89, 89, 89, 56, 35, -200]
marker-names [u'Toner Cartridge OKI DATA CORP', u'Toner Cartridge OKI
DATA CORP', u'Toner Cartridge OKI DATA CORP', u'Toner Cartridge OKI
DATA CORP', u'Image Drum Unit OKI DATA CORP', u'Image Drum Unit OKI
DATA CORP', u'Image Drum Unit OKI DATA CORP', u'Image Drum Unit OKI
DATA CORP', u'Belt Unit OKI DATA CORP', u'Fuser Unit OKI DATA CORP',
u'Waste Toner box OKI DATA CORP']
marker-types [u'toner', u'toner', u'toner', u'toner', u'opc', u'opc',
u'opc', u'opc', u'transferUnit', u'fuser', u'wasteToner']
media-col-supported [u'media-color', u'media-key', u'media-size', u'media-type']
media-default iso_a4_210x297mm
media-supported [u'iso_a4_210x297mm', u'na_letter_8.5x11in',
u'na_legal_8.5x14in', u'na_foolscap_8.5x13in', u'iso_a5_148x210mm',
u'jis_b5_182x257mm', u'iso_a6_105x148mm', u'na_monarch_3.875x7.5in',
u'iso_dl_110x220mm', u'iso_c5_162x229mm', u'na_number-10_4.125x9.5in',
u'na_executive_7.25x10.5in', u'na_number-9_3.875x8.875in',
u'adobe_OKLegal_8.5x13.5in', u'custom_min_63.8528x147.814mm',
u'custom_max_8.51389x47.25in']
multiple-document-handling-supported
[u'separate-documents-uncollated-copies',
u'separate-documents-collated-copies']
multiple-document-jobs-supported True
multiple-operation-time-out 300
natural-language-configured en_US
notify-attributes-supported [u'printer-state-change-time',
u'notify-lease-expiration-time', u'notify-subscriber-user-name']
notify-events-default [u'job-completed']
notify-events-supported [u'job-completed', u'job-config-changed',
u'job-created', u'job-progress', u'job-state-changed', u'job-stopped',
u'printer-added', u'printer-changed', u'printer-config-changed',
u'printer-deleted', u'printer-finishings-changed',
u'printer-media-changed', u'printer-modified', u'printer-restarted',
u'printer-shutdown', u'printer-state-changed', u'printer-stopped',
u'server-audit', u'server-restarted', u'server-started',
u'server-stopped']
notify-lease-duration-default 86400
notify-lease-duration-supported (0, 2147483647)
notify-max-events-supported [100]
notify-pull-method-supported [u'ippget']
notify-schemes-supported [u'mailto', u'rss']
number-up-default 1
number-up-supported [1, 2, 4, 6, 9, 16]
operations-supported [2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 16, 17, 18,
19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 34, 35, 37, 38, 16385, 16386,
16387, 16388, 16389, 16390, 16391, 16392, 16393, 16394, 16395, 16396,
16397, 16398, 16399, 16423]
orientation-requested-default None
orientation-requested-supported [3, 4, 5, 6]
page-ranges-supported True
pages-per-minute 20
pdl-override-supported [u'not-attempted']
port-monitor none
port-monitor-supported [u'none', u'tbcp']
printer-commands [u'AutoConfigure', u'Clean', u'PrintSelfTestPage']
printer-current-time (IPP_TAG_DATE)
printer-error-policy stop-printer
printer-error-policy-supported [u'abort-job', u'retry-current-job',
u'retry-job', u'stop-printer']
printer-info OKI-MC560
printer-is-accepting-jobs True
printer-is-shared True
printer-location Local Printer
printer-make-and-model OKI MC560 PS
printer-more-info http://localhost:631/printers/MC560
printer-name MC560
printer-op-policy default
printer-op-policy-supported [u'authenticated', u'default']
printer-settable-attributes-supported [u'printer-info', u'printer-location']
printer-state 3
printer-state-change-time 1443808170
printer-state-message Ready to print.
printer-state-reasons [u'toner-low-report']
printer-type 8425548
printer-up-time 1443819651
printer-uri-supported [u'ipp://localhost:631/printers/MC560']
queued-job-count 0
server-is-sharing-printers True
uri-authentication-supported [u'requesting-user-name']
uri-security-supported [u'none']

**Comment by jacobmarble** [comment]
I installed CentOS 6 in a VM. It looks like the UUID is missing from the attributes reported by CUPS. Your attributes confirm the same issue.

Start the connector, wait for the "ready to rock" message, kill the connector, and send me the log file at `/tmp/gcp-cups-connector.INFO`

**Comment by holckj** [comment]
Here it is :

Log file created at: 2015/10/03 00:14:12
Running on machine: karoline
Binary: Built with gc go1.5.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1003 00:14:12.655245   30107 gcp-cups-connector.go:34] Google Cloud
Print CUPS Connector version DEV-linux
I1003 00:14:13.952233   30107 core.go:92] connected to CUPS server
/var/run/cups/cups.sock:631 encrypting IF REQUESTED
I1003 00:14:13.955286   30107 avahi.go:261] Local printing enabled
(Avahi client is running).
I1003 00:14:14.418133   30107 printermanager.go:165] Synchronizing
printers, stand by
E1003 00:14:14.579150   30107 printermanager.go:227] Failed to
register printer MC560: https://www.google.com/cloudprint/register
call failed: Ugyldig beskrivelse af skyenhed.
I1003 00:14:14.579204   30107 printermanager.go:217] Finished
synchronizing 0 printers
E1003 00:14:14.579348   30107 gcp-cups-connector.go:140] Ready to rock
as proxy 'jesper.holck.MC560' and in local mode
E1003 00:14:21.429863   30107 gcp-cups-connector.go:153] Shutting down
I1003 00:14:21.430710   30107 internal-xmpp.go:582] XMPP connection was closed

**Comment by jacobmarble** [comment]
Well, I'm not sure why your error message says "Ugyldig beskrivelse af
skyenhed"; mine explicitly says the UUID field is missing. I'll write a
patch.

**Comment by holckj** [comment]
:-)
Den 03/10/2015 00.23 skrev "Jacob Marble" <notifications@github.com>:

**Comment by jacobmarble** [comment]
@holckj let me know if that works for you.

**Comment by holckj** [comment]
Unfortunately, it doesn't seem to work just yet.

With no gcp-cups-connector.config.json file, I can run gcp-cups-connector without errors. Here is a snippet from the INFO log file:

Log file created at: 2015/10/04 12:52:30
Running on machine: karoline
Binary: Built with gc go1.5.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1004 12:52:30.447696   15560 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version DEV-linux
I1004 12:52:30.448552   15560 gcp-cups-connector.go:42] No config file was found, so using defaults
I1004 12:52:30.451438   15560 core.go:92] connected to CUPS server /var/run/cups/cups.sock:631 encrypting IF REQUESTED
I1004 12:52:30.453840   15560 avahi.go:261] Local printing enabled (Avahi client is running).
I1004 12:52:30.455041   15560 printermanager.go:165] Synchronizing printers, stand by
I1004 12:52:30.540001   15560 printermanager.go:217] Finished synchronizing 1 printers
I1004 12:52:30.543323   15560 printermanager.go:118] Registered MC560 locally
E1004 12:52:30.543548   15560 gcp-cups-connector.go:147] Ready to rock in local-only mode
I1004 12:53:30.544277   15560 printermanager.go:165] Synchronizing printers, stand by
I1004 12:53:30.546896   15560 printermanager.go:198] Printers are already in sync; there are 1
I1004 12:54:30.547110   15560 printermanager.go:165] Synchronizing printers, stand by

When I in Google Chrome go to chrome://devices, I can now see "OKI-MC560" under the heading "New devices". When I click the "Register"-button, I get the message "Do you wish to register the printer OKI-MC560 to Google Cloud Print?". I click "Register", and the reply is "You must confirm registration on the printer, check it now", I think. This message is only showed very briefly. The next message is "Could not complete registration. An error has occurred. Please check your printer and try again."

If I then go to google.com/cloudprint, the printer isn't there.

If I do create a gcp-cups-connector.config.json file and allow external access, I still get messages about an erroneous device description:

E1005 14:42:16.551485   15881 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
E1005 14:42:18.394764   15881 printermanager.go:227] Failed to register printer MC560: https://www.google.com/cloudprint/register call failed: Ugyldig beskrivelse af skyenhed.
E1005 14:42:18.394964   15881 gcp-cups-connector.go:140] Ready to rock as proxy 'jespersMC560' and in local mode

**Comment by jacobmarble** [comment]
I want to make sure that you have the latest code. Please run `git pull` from the directory `$GOPATH/src/github.com/google/cups-connector`. After that, rebuild with `go get github.com/google/cups-connector/...`.

**Comment by holckj** [comment]
OK:

$ cd ~/go/src/github.com/google/cups-connector/
$ ls
cdd           cups  gcp-cups-connector       lib      manager  privet     snmp
CONTRIBUTING  gcp   gcp-cups-connector-util  LICENSE  monitor  README.md  xmpp
$ git pull
Already up-to-date.
$ go get github.com/google/cups-connector/...
$ cd $GOPATH/bin
$ sudo ./gcp-cups-connector
[sudo] password for holck: 
E1005 19:58:28.185551   23682 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
E1005 19:58:29.950678   23682 printermanager.go:227] Failed to register printer MC560: https://www.google.com/cloudprint/register call failed: Ugyldig beskrivelse af skyenhed.
E1005 19:58:29.950918   23682 gcp-cups-connector.go:140] Ready to rock as proxy 'jespersMC560' and in local mode
Ready to rock as proxy 'jespersMC560' and in local mode
^CE1005 19:58:34.833833   23682 gcp-cups-connector.go:153] Shutting down

**Comment by jacobmarble** [comment]
I'm stumped.

Is the PPD you are using the same as the one you referenced before? Print backends can change PPDs locally. You could check the MD5 checksum of /etc/cups/ppd/your-printer.ppd.

Add a line of code to `github.com/google/cups-connector/gcp/gcp.go` at line 260 (add line 261):
```
fmt.Println(capabilities)
```
This will spit out the Cloud Device Description in question, which will tell me exactly what is invalid.

**Comment by holckj** [comment]
Yes, the PPD file now in /etc/cups/ppd/MC560.ppd is exactly the same as the one I referenced earlier. Here are the results of adding the extra line:

sudo ./gcp-cups-connector
E1005 21:08:19.572057   26016 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
{"version":"1.0","printer":{"supported_content_type":[{"content_type":"application/pdf"},{"content_type":"application/postscript"},{"content_type":"image/gif"},{"content_type":"image/jpeg"},{"content_type":"image/png"},{"content_type":"image/tiff"},{"content_type":"text/plain"}],"printing_speed":{"option":[{"speed_ppm":20}]},"marker":[{"vendor_id":"Toner Cartridge OKI DATA CORP","type":"TONER","color":{"type":"CUSTOM","custom_display_name_localized":[{"locale":"EN","value":"Toner Cartridge OKI DATA CORP"}]}},{"vendor_id":"Toner Cartridge OKI DATA CORP","type":"TONER","color":{"type":"CUSTOM","custom_display_name_localized":[{"locale":"EN","value":"Toner Cartridge OKI DATA CORP"}]}},{"vendor_id":"Toner Cartridge OKI DATA CORP","type":"TONER","color":{"type":"CUSTOM","custom_display_name_localized":[{"locale":"EN","value":"Toner Cartridge OKI DATA CORP"}]}},{"vendor_id":"Toner Cartridge OKI DATA CORP","type":"TONER","color":{"type":"CUSTOM","custom_display_name_localized":[{"locale":"EN","value":"Toner Cartridge OKI DATA CORP"}]}}],"vendor_capability":[{"id":"number-up","type":"SELECT","select_cap":{"option":[{"value":"1","is_default":true,"display_name_localized":[{"locale":"EN","value":"1"}]},{"value":"2","is_default":false,"display_name_localized":[{"locale":"EN","value":"2"}]},{"value":"4","is_default":false,"display_name_localized":[{"locale":"EN","value":"4"}]},{"value":"6","is_default":false,"display_name_localized":[{"locale":"EN","value":"6"}]},{"value":"9","is_default":false,"display_name_localized":[{"locale":"EN","value":"9"}]},{"value":"16","is_default":false,"display_name_localized":[{"locale":"EN","value":"16"}]}]},"display_name_localized":[{"locale":"EN","value":"Pages per sheet"}]}],"duplex":{"option":[{"type":"NO_DUPLEX","is_default":true},{"type":"LONG_EDGE","is_default":false},{"type":"SHORT_EDGE","is_default":false}]},"page_orientation":{"option":[{"type":"AUTO","is_default":true},{"type":"PORTRAIT","is_default":false},{"type":"LANDSCAPE","is_default":false}]},"copies":{"default":1,"max":9999},"margins":{"option":[{"type":"STANDARD","top_microns":4586,"right_microns":4586,"bottom_microns":4586,"left_microns":4586,"is_default":true}]},"fit_to_page":{"option":[{"type":"NO_FITTING","is_default":true},{"type":"FIT_TO_PAGE","is_default":false}]},"media_size":{"option":[{"name":"ISO_A4","width_microns":210000,"height_microns":297000,"is_continuous_feed":false,"is_default":true,"vendor_id":"A4","custom_display_name_localized":[{"locale":"EN","value":"A4"}]},{"name":"NA_LETTER","width_microns":215900,"height_microns":279400,"is_continuous_feed":false,"is_default":false,"vendor_id":"Letter","custom_display_name_localized":[{"locale":"EN","value":"Letter"}]},{"name":"NA_LEGAL","width_microns":215900,"height_microns":355600,"is_continuous_feed":false,"is_default":false,"vendor_id":"Legal","custom_display_name_localized":[{"locale":"EN","value":"Legal"}]},{"name":"NA_FOOLSCAP","width_microns":215900,"height_microns":330200,"is_continuous_feed":false,"is_default":false,"vendor_id":"FanFoldGermanLegal","custom_display_name_localized":[{"locale":"EN","value":"Fan Fold German Legal"}]},{"name":"ISO_A5","width_microns":148000,"height_microns":210000,"is_continuous_feed":false,"is_default":false,"vendor_id":"A5","custom_display_name_localized":[{"locale":"EN","value":"A5"}]},{"name":"JIS_B5","width_microns":182000,"height_microns":257000,"is_continuous_feed":false,"is_default":false,"vendor_id":"B5","custom_display_name_localized":[{"locale":"EN","value":"B5 (JIS)"}]},{"name":"ISO_A6","width_microns":105000,"height_microns":148000,"is_continuous_feed":false,"is_default":false,"vendor_id":"A6","custom_display_name_localized":[{"locale":"EN","value":"A6"}]},{"name":"NA_MONARCH","width_microns":98425,"height_microns":190500,"is_continuous_feed":false,"is_default":false,"vendor_id":"EnvMonarch","custom_display_name_localized":[{"locale":"EN","value":"Monarch"}]},{"name":"ISO_DL","width_microns":110000,"height_microns":220000,"is_continuous_feed":false,"is_default":false,"vendor_id":"EnvDL","custom_display_name_localized":[{"locale":"EN","value":"DL Envelope"}]},{"name":"ISO_C5","width_microns":162000,"height_microns":229000,"is_continuous_feed":false,"is_default":false,"vendor_id":"EnvC5","custom_display_name_localized":[{"locale":"EN","value":"C5 (ISO)"}]},{"name":"NA_NUMBER_10","width_microns":104775,"height_microns":241300,"is_continuous_feed":false,"is_default":false,"vendor_id":"Env10","custom_display_name_localized":[{"locale":"EN","value":"Env10"}]},{"name":"NA_EXECUTIVE","width_microns":184150,"height_microns":266700,"is_continuous_feed":false,"is_default":false,"vendor_id":"Executive","custom_display_name_localized":[{"locale":"EN","value":"Executive"}]},{"name":"NA_NUMBER_9","width_microns":98425,"height_microns":225425,"is_continuous_feed":false,"is_default":false,"vendor_id":"Env9","custom_display_name_localized":[{"locale":"EN","value":"Env9"}]}]},"collate":{"default":true},"reverse_order":{"default":false}}}
E1005 21:08:21.116375   26016 printermanager.go:227] Failed to register printer MC560: https://www.google.com/cloudprint/register call failed: Ugyldig beskrivelse af skyenhed.

**Comment by jacobmarble** [comment]
Your CDD has a markers section; mine doesn't. Do you have `snmp_enable` set to true in your config file?

I'll be near an OKI MC883 tomorrow, I'll see if the same problem happens when I enable SNMP.

**Comment by holckj** [comment]
No, snmp doesn't seem to be enabled:
$ sudo grep -i snmp gcp-cups-connector.config.json 
  "snmp_enable": false,
  "snmp_community": "public",
  "snmp_max_connections": 100,
Thank you for your effort :-)

**Comment by jacobmarble** [comment]
I'm sorry, of course SNMP isn't at fault. You listed the attributes earlier:
```
marker-names [u'Toner Cartridge OKI DATA CORP', u'Toner Cartridge OKI
DATA CORP', u'Toner Cartridge OKI DATA CORP', u'Toner Cartridge OKI
DATA CORP', u'Image Drum Unit OKI DATA CORP', u'Image Drum Unit OKI
DATA CORP', u'Image Drum Unit OKI DATA CORP', u'Image Drum Unit OKI
DATA CORP', u'Belt Unit OKI DATA CORP', u'Fuser Unit OKI DATA CORP',
u'Waste Toner box OKI DATA CORP']
```

On my test workstation, markers aren't listed because there's no printer to probe. The problem is that your printer names all of the toner cartridges with the same name: "Toner Cartridge OKI DATA CORP". I can fix this; we'll just ignore all markers if some share names.

Give me a day or two to write a patch.

**Comment by holckj** [comment]
I'm sorry, but it still doesn't work for me ... Just did a fresh download and build, but get the same message:

$ sudo ./gcp-cups-connector
E1015 11:55:05.263770   22325 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
E1015 11:55:07.282033   22325 printermanager.go:227] Failed to register printer MC560: https://www.google.com/cloudprint/register call failed: Ugyldig beskrivelse af skyenhed.
E1015 11:55:09.461185   22325 gcp-cups-connector.go:141] Ready to rock as proxy 'MC560proxy' and in local mode
Ready to rock as proxy 'MC560proxy' and in local mode
E1015 11:56:09.754055   22325 printermanager.go:227] Failed to register printer MC560: https://www.google.com/cloudprint/register call failed: Ugyldig beskrivelse af skyenhed.

**Comment by jacobmarble** [comment]
@holckj I'm on vacation for a few days, and I can see that this needs my focused attention, so I'm going to ignore it until I get back.

**Comment by holckj** [comment]
Any news?
