### ISSUE TITLE
Document name / configurable / remove gcp_longID

### ISSUE THREAD

**Issue by erickufrin** [google/cups-connector#103]
Is it possible to configure GCP to not include the gcp_LONGID in the document name? If not, can this feature be added/configurable? (thanks in advance)

We have an intelligent network LPR queue that holds jobs after submission. The user must release the job after logging in with their badge at the printer.

I would say typically users just "print all" when at the console of the printer. But a use case would be where a user sent multiple jobs and does not care to print certain jobs.

Example: user prints the wrong thing, realizes it, then sends the correct job. When they go to the printer they would not be able to distinguish between the wrong job and the correct/desired print job.

These long values prefixing the job are so long the actual job name is truncated/unvisible.

(attached) is an example of the document names as they populate the queue.

<img width="661" alt="screen shot 2015-10-04 at 12 45 06 pm" src="https://cloud.githubusercontent.com/assets/14966495/10269248/e2ac82ce-6a96-11e5-8662-7c88ca344bb7.png">

**Comment by jacobmarble** [comment]
I think that's a good idea. It's helpful for development and admin purposes, so let's make it optional, with the default "off".

**Comment by erickufrin** [comment]
Thank you! I appreciate the quick response & fix! :-D

**Comment by jacobmarble** [comment]
No prob. :)

**Comment by erickufrin** [comment]
Tested. Working great now w/o the long prefix. :+1:

**Comment by jacobmarble** [comment]
Made my day :)
