### ISSUE TITLE
Consider using go-flags instead of builtin flag package

### ISSUE THREAD

**Issue by jay0lee** [google/cups-connector#105]
I think the project is starting to outgrow Go's builtin flag capabilities:
* `gcp-cups-connector-util --help` is getting messy. Being able to group the options would definitely help.
* gcp-cups-connector-util.go is getting a rather large if-then-else tree and that will grow even larger when ACL functionality is added.

@jacobmarble how would you feel about moving to:

https://github.com/jessevdk/go-flags

for flag processing? The grouping alone should make `gcp-cups-connector-util` a lot cleaner.

**Comment by jacobmarble** [comment]
Yes, I can look at that. I'm having similar thoughts about glog.

**Comment by jacobmarble** [comment]
I'm planning to use a different flags library, and also change the way we call utilities, so that `$ gcp-cups-connector-util -toolname -flag1 -flag2` becomes `$ gcp-cups-connector-util toolname -flag1 -flag2`

**Comment by jacobmarble** [comment]
Fixed in #122
