### ISSUE TITLE
Works perfectly with one account but not another

### ISSUE THREAD

**Issue by timmrogers** [google/cups-connector#109]
I've finally sorted out my problems with CUPS, with our Brother HL5470-DW printers, with encryption, and so on - and installed the latest version of the cups-connector. I am using local mode. And when I am logged into Chrome with my @gmail.com account, it works perfectly!

However, when I use my Google Apps for Education account (@oakhillschool.net), none of the printers share by the cups-connector appear! I can see some that have been shared in other ways, but not the ones managed by the cups-connector.

Any suggestions?

Thank you!

**Comment by jay0lee** [comment]
Hi Tim,

A few questions:

* Does your school account require a VPN or Proxy?
* From the school account, can you reach the CUPS server (ping or open web page)?
* When you switch accounts, are you remaining on the same wired or WiFi connection?

**Comment by timmrogers** [comment]
Thanks for the reply.

No VPN nor proxy.
Yes, I can always ping and ssh to the CUPS server.
Yes, I am always using the same Wi-Fi connection.

The strange thing is that I am merely changing the account that I am using to log into Google. Absolutely nothing else is changing on my computer or network. In fact, right now, I am logged in in one Chrome window to my @oakhillschool.net account and another in my @gmail.com account - and one works with the cups-connector printers and one does not.

Also: I see that no Cloud Print printers show up at all when I log in with an old @gmail.com account that I don't use often. Only with my timmrogers@gmail.com account.

Could I have old cups-connector configuration files around from my earlier attempts to get this working? I'll look...

**Comment by jay0lee** [comment]
Thanks, is this a Chrome OS device or something else? Can you try installing this extension:

https://chrome.google.com/webstore/detail/mdns-browser/kipighjpklofchgbdgclfaoccdlghidp

when opening mDNS Browser, you should see (among other items) a listing for "_privet" and the IP address of your cups-connector server. Do you see that on both profiles? If you can't see it in the profile, some network setting is blocking cups-connector's mDNS broadcast.

**Comment by timmrogers** [comment]
I'm working with Google Chrome on a MacBook Pro (OS X 10.10). 

I also tried it on a Chromebook using my @oakhillschool.net account. 

I'll try to extension.

**Comment by timmrogers** [comment]
While logged into my @oakhillschool.net account in Google Chrome, and running Apps | mDNS Browser, _prvet shows 192.16.0.5 - which is the IP address of my CUPS server.

**Comment by jay0lee** [comment]
OK, can you try browsing to:

chrome://policy

and print the page you see there to a PDF and attach it here?

**Comment by timmrogers** [comment]
Here you go. (I notice that my timmrogers@gmail.com has no mandatory policies, while this has a couple. Might these be the issue?)

Hmmm...GitHub will not allow me to attach the PDF. It says "Something went really wrong, and we can't process that file."

Here is the information as text:

User policies
User:
trogers@oakhillschool.net
Client ID:
28335CEB-E533-43BF-A56B-60612771C39C
Last fetched:
2 hours ago
Fetch interval:
3 hours
Status:
Policy cache OK
Chrome policies

Applies to	Level	Policy name	Policy value	Status
Current user
Mandatory
ExtensionInstallBlacklist
nccnonfgafoenakjedibnklpgdgjakkh
OK
Current user
Mandatory
MaxInvalidationFetchDelay
10000
OK

**Comment by timmrogers** [comment]
Chrome just popped up two announcements, saying that it had found "7 new printers" and suggesting that I add them to my Google Chrome print so I could print from anywhere. 

I didn't. I notice that those printers are still not available in Cloud Print.

**Comment by jacobmarble** [comment]
Tim, that "7 new printers" popup is a Chrome bug. You'll never need to
respond to it with a CUPS Connector printer.

However, it does indicate that Chrome saw the mDNS announcement, so that's
good.

**Comment by timmrogers** [comment]
Thanks. 

I see that it gave the announcement (twice) again. That might be a problem, if it is making that announcement every few minutes to everyone on campus who is using Google Chrome.

**Comment by jacobmarble** [comment]
@timmrogers I suggest that you become a squeaky wheel here: crbug.com/540847
I talked to the engineer responsible for this yesterday; he says this is a pretty easy bug to fix.

**Comment by timmrogers** [comment]
I voted for the bug. Your report seemed more than clear!

Leaving aside the Google bug, any ideas as to why the printers are available in one account and not another?

**Comment by jacobmarble** [comment]
(punting to @jay0lee)

**Comment by jay0lee** [comment]
Can you share screenshots of what you see when you hit CYRL+P on a web page in both accounts?

**Comment by jay0lee** [comment]
CTRL+P, sorry for mobile typo

**Comment by timmrogers** [comment]
You can see the account name in the screenshots. I am looking for the printer called "ohs-computer_lab". It is available in the @gmail.com account, but not the @oakhillschool.net account.

<img width="1399" alt="oakhillschool account" src="https://cloud.githubusercontent.com/assets/8450844/10352659/6aee69b6-6d05-11e5-8aff-08028b005d11.png">

<img width="1431" alt="gmail account" src="https://cloud.githubusercontent.com/assets/8450844/10352689/9cb716d2-6d05-11e5-92f8-c828164779bb.png">

**Comment by jay0lee** [comment]
@timmrogers we don't expect the GCP version of the printer to show under Google Cloud Print for your school account unless you've shared the printer and accepted it.We're looking for the local version. Does it show further up the list under a "Local Destinations heading?

**Comment by timmrogers** [comment]
That makes sense - but a couple of things are confusing to me.

First, the GCP version of the printer DOES show up under Google Cloud Print
for my @gmail.com account. But on the same machine, same network, same
everything, it does not show up there for my @oakhillschool.net account. I
can't imagine why that would be.

Second, no printers show up on a Chromebook when logged in under my @
oakhillschool.net account. Which is, for me, the point of the entire
exercise!

(I haven't tried the Chromebook with my @gmail.com acount, but I can do
that and let you know.)

But no. "ohs-computer_lab" and the other printers shared via the
gcp-cups-connector do not appear under Local Destinations - at least, not
by the names that I expect. I DO see new entries there though. Perhaps that
is the gcp-cups-connector doing its thing? Or could it be the CUPS server?

I'm afraid that the difference between the behavior of the two accounts has
my head spinning a bit!

Thanks.

**Comment by jay0lee** [comment]
> First, the GCP version of the printer DOES show up under Google Cloud Print
> for my @gmail.com account. But on the same machine, same network, same
> everything, it does not show up there for my @oakhillschool.net account. I
> can't imagine why that would be.

Google CloudPrint printers are shared between Google accounts. It doesn't matter what network or device you are on, what matters is if it's shared with your Google account. You can go to google.com/cloudprint from the @gmail.com account and share the printer with your school account or you can set share_scope in your gcp-cups-connector config file to automatically share all your GCP printers with your school account.

> Second, no printers show up on a Chromebook when logged in under my @
> oakhillschool.net account. Which is, for me, the point of the entire
> exercise!

If local printing is functional and you're connected to the same network, the local version of your printer should show under "Local Destinations" when you hit CTRL+P on the Chromebook and Change the printer.

**Comment by timmrogers** [comment]
OK - I'll try a few things and get back to you.

Thanks again.
