### ISSUE TITLE
Illegal Instruction (core dumped)

### ISSUE THREAD

**Issue by dleigh** [google/cups-connector#112]
So I just downloaded gcp-cups-connector-linux-386-2015.10.05.tar.gz and put it on an Ubuntu 14.04.3 server with CUPS already running and working.  When I run gcp-cups-connector or gcp-cups-connector-util -init from the command line as root, I get "illegal instruction (core dumped)".  Where do I go from here?
Thanks!

**Comment by jay0lee** [comment]
What does:

`uname -m`

Show on the Ubuntu computer? If it's x86_64 you should be downloading the AMD64 version.

Jay

**Comment by dleigh** [comment]
This is what it shows : 

 

root@i-server:~# uname -m

i686

Press any key to continue...

 

 <mailto:david@leighweb.com> SigLeighweb

 

De : Jay Lee [mailto:notifications@github.com] 
Envoyé : lundi 12 octobre 2015 12:36
À : google/cups-connector
Cc : dleigh
Objet : Re: [cups-connector] Illegal Instruction (core dumped) (#112)

 

What does:

uname -m

Show on the Ubuntu computer? If it's x86_64 you should be downloading the AMD64 version.

Jay

**Comment by jay0lee** [comment]
I have a Ubuntu 14.0.4 386 box and tried to reproduce your issue but could not. Is there anything special about this system's configuration? I noticed that after you ran uname -m it said:

Press any key to continue...

which is not normal for a Linux box, are you running some special configuration?

**Comment by jay0lee** [comment]
Hi dleigh, any update on this or should we close out?

**Comment by dleigh** [comment]
I'm still waiting for some help. Some steps to debug, etc.

== David Leigh == david@leighweb.com == http://david.leighweb.com == Sent
from my Android phone ==

**Comment by dleigh** [comment]
Is there anything that I can do to create more useful output for the error I'm seeing?  Thanks.

**Comment by jay0lee** [comment]
I noticed that after you ran uname -m it said:

Press any key to continue...

which is not normal for a Linux box, are you running some special configuration?

**Comment by dleigh** [comment]
Oh...for the "press any key to continue...." message, that's because I ran the uname -m command from within Midnight Commander.

**Comment by jay0lee** [comment]
Are you also running cups-connector from MC?

Can you try compiling cups-connector with the instructions at:

https://github.com/google/cups-connector/wiki/Build-from-source

and see if your compiled version works? The binaries are relatively new and don't work on all systems.

**Comment by dleigh** [comment]
I don't remember specifically HOW I installed it but I think I would have followed the install instructions in the wiki.  I happened to execute the test instructions from within MC because I typically work from within MC as opposed to the command line.

I'll try the build from source route and see what happens.  I'll post back.
Thanks!

**Comment by jacobmarble** [comment]
@dleigh I assume that you figured something out. Feel free to re-open.
