### ISSUE TITLE
Device registration fails: request canceled while waiting for connection

### ISSUE THREAD

**Issue by ifjq217** [google/cups-connector#115]
gcp-cups-connector-util fails during device registration.

Output:
Visit https://www.google.com/device, and enter this code. I'll wait for you.
GGCA-YRWH
2015/10/16 17:53:47 Get https://www.google.com/cloudprint/createrobot?oauth_client_id=539833558011-23iq8btpgas80nrs3o7mv99hm95d4dv6.apps.googleusercontent.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by jacobmarble** [comment]
Tell me about your internet connection. Are you in a remote location, or is the internet connection usually slow?

**Comment by ifjq217** [comment]
25Mbps cable. I'm not seeing any other connection problems or slowness.  It consistently happens in the same place in the script.

**Comment by ifjq217** [comment]
A few additional details... The timeout error occurs about 5 seconds after I enter the code on the Google devices site.  I'm using Fedora 22 so I built go and the connector binaries from source.

**Comment by jacobmarble** [comment]
The default timeout is 5s when /createrobot is called. By then, two other HTTP requests have already succeeded, so this is strange.

When you call `gcp-cups-connector-util -init` try adding this flag: `-gcp-api-timeout 60s`

**Comment by jacobmarble** [comment]
Also, can you visit this url, without error, from that same Fedora box?
https://www.google.com/cloudprint/simulate.html

**Comment by jacobmarble** [comment]
I'm looking at the code that generates the error you are receiving. For whatever reason, you can't connect to www.google.com/cloudprint. It's not that the data is bad, or that an error is returned, but that the connection isn't made within 5 seconds.

The OAuth HTTP requests that have succeeded by this time are talking to accounts.google.com, while the /createrobot HTTP request is talking to www.google.com.

**Comment by ifjq217** [comment]
The longer timeout using -gcp-api-timeout seems to have worked.  The json config file has been successfully created.  It's hard to imagine, but perhaps the additional DNS lookup and SSL handshake for www.google.com exceeded the 5 second timeout.  Comcast cable isn't exactly known for low latency.  I am using the Google public DNS because it's usually faster than my ISP's DNS.

**Comment by ifjq217** [comment]
Thanks for all the help.  This project has saved my Canon MX892 which lost it's ability to cloud print due to some Google service changes and Canon's inability to update the firmware.

**Comment by jacobmarble** [comment]
OK, I'm glad we found a solution. I'm going to change the default to 30 seconds.
