### ISSUE TITLE
Suggested improvement of “Run automatically on boot” section in Wiki / Install

### ISSUE THREAD

**Issue by KJS18** [google/cups-connector#116]
The “Run automatically on boot” section of the new “Install” Wiki is highly likely to prove problematic for the less experienced.
    1. I present evidence here that the ampersanded line in /etc/rc.local is problematic and needs revising.
    2. There is zero feedback from this line when problems occur (and they do).

The inclusion of several logsave commands in the rc.local file provided very revealing feedback:
```shell
#!/bin/sh -e
# 
# rc.local 
# 
# This script is executed at the end of each multiuser runlevel. 
# Make sure that the script will "exit 0" on success or any other 
# value on error. 
# 
# In order to enable or disable this script just change the execution 
# bits. 
# 
# By default this script does nothing. 
logsave /tmp/rc.local_active_directory.log pwd 
logsave /tmp/rc.local_current_path.log echo $PATH 
# 
# After running gcp-cups-connector-util -init 
# ...the following code appears to be working 
sleep 60 
logsave /tmp/rc.local_gcp_cups_connector_line.log su --login --command /usr/sbin/gcp-cups-connector admin & 
# 
# whereas the following line leads to a "command not found" error 
# logsave /tmp/rc.local_gcp_cups_connector_line.log su --login --command gcp-cups-connector admin & 
# 
exit 0
```

contents of /tmp/rc.local_active_directory.log (blank lines removed)
```text
Log of pwd 
Mon Oct 19 18:38:47 2015 
/ 
Mon Oct 19 18:38:47 2015 
```

contents of /tmp/rc.local_current_path.log (blank lines removed)
```text
Log of echo /sbin:/usr/sbin:/bin:/usr/bin 
Mon Oct 19 18:38:47 2015 
/sbin:/usr/sbin:/bin:/usr/bin 
Mon Oct 19 18:38:47 2015 
```

**Conclusions**

Despite the fact that whilst /etc/rc.local was being processed, $PATH = /sbin:/usr/sbin:/bin:/usr/bin,
when I put the binaries in /usr/sbin (so that “gcp‑cups‑connector” ought to be findable within the command search path), a rather unexpected “command not found” error occurred (see Example 1 below) when the ampersand line in /etc/rc.local consisted of:
```shell
su --login --command gcp-cups-connector admin &
```
Example 1: Contents of rc.local_gcp_cups_connector_line.log (blank lines removed)
```text
Log of su --login --command gcp-cups-connector admin 
Mon Oct 19 12:20:37 2015 
-su: gcp-cups-connector: command not found 
su died with exit status 127 
Mon Oct 19 12:20:37 2015
```
so during interpretation of the rc.local script, $PATH seems to be ignored. 

However when the full path was included, everything worked OK (see example 2):

Example 2: Contents of rc.local_gcp_cups_connector_line.log (blank lines removed)
```text
Log of su --login --command /usr/sbin/gcp-cups-connector admin 
Mon Oct 19 12:31:26 2015 
E1019 12:31:26.748528    2295 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version 2015.10.05-linux 
Google Cloud Print CUPS Connector version 2015.10.05-linux 
E1019 12:31:26.839178    2295 gcp-cups-connector.go:148] Ready to rock in local-only mode 
Ready to rock in local-only mode
```
**Summary**

My investigation strongly suggests that it is safest to specify the full path to the “gcp-cups-connector” binary (the way I ended up doing).

**Footnote (software/hardware used)**

Operating system:
    Ubuntu 14.04 LTS x86-64 (GUI version)
Hardware:
    Model = Gigabyte Brix
    CPU = Intel Celeron  N2807
    Graphics = Intel Bay Trail

**Comment by KJS18** [comment]
I have not investigated it but increasing the "sleep" time might also fix the problem. However (a) the required delay may vary between machines and (b) specifying the full path would mean more consistency and would get the connector up and running more quickly.

**Comment by jacobmarble** [comment]
- I agree that the delay can vary between machines, and I consider 60 seconds to be generous, so should work for most users.
- I have updated the wiki per your suggestion.
