### ISSUE TITLE
Cannot unmarshal array

### ISSUE THREAD

**Issue by akorobkin** [google/cups-connector#117]
Build 07/31, connector kept dying multiple times with this error: 

Log file created at: 2015/10/22 18:35:27
Running on machine: printserver5
Binary: Built with gc go1.4.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1022 18:35:27.899639    2427 connector.go:32] Google Cloud Print CUPS Connector version 2015.07.31-linux
I1022 18:35:28.339488    2427 core.go:92] connected to CUPS server /var/run/cups/cups.sock:631 encrypting IF REQUESTED
F1022 18:35:30.221703    2427 connector.go:97] 74 errors: json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption, json: cannot unmarshal array into Go value of type cdd.PrintingSpeedOption
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc20802c001, 0x0, 0x0, 0x0)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:766 +0xcd
github.com/golang/glog.(*loggingT).output(0xb8ae80, 0xc200000003, 0xc20805c000, 0x969f30, 0xc, 0x61, 0x0)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:720 +0x2d2
github.com/golang/glog.(*loggingT).printDepth(0xb8ae80, 0xc200000003, 0x1, 0xc208457f68, 0x1, 0x1)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:646 +0x1d3
github.com/golang/glog.(*loggingT).print(0xb8ae80, 0xc200000003, 0xc208457f68, 0x1, 0x1)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:637 +0x57
github.com/golang/glog.Fatal(0xc208457f68, 0x1, 0x1)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:1125 +0x50
main.main()
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/connector/connector.go:97 +0x11b5

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xb8ae80)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 15 [IO wait]:
net.(*pollDesc).Wait(0xc208390300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208390300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083902a0, 0xc2083ac400, 0x400, 0x400, 0x0, 0x7f062da28dd8, 0xc2083b6f08)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c0b0, 0xc2083ac400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208394630, 0x7f062da2a668, 0xc20802c0b0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208177340, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208177340, 0xc2083b4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
bufio.(*Reader).fill(0xc2083aaba0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadByte(0xc2083aaba0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:196 +0x86
encoding/xml.(*Decoder).getc(0xc208378840, 0x0)
	/usr/local/go/src/encoding/xml/xml.go:852 +0xad
encoding/xml.(*Decoder).rawToken(0xc208378840, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/xml/xml.go:512 +0x147
encoding/xml.(*Decoder).Token(0xc208378840, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/xml/xml.go:247 +0x850
github.com/google/cups-connector/xmpp.readStartElement(0xc208378840, 0xc2083e4930, 0x0, 0x0)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/internal-xmpp.go:513 +0x4b
github.com/google/cups-connector/xmpp.(*internalXMPP).dispatchIncoming(0xc2083d96d0, 0xc2083e6a80)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/internal-xmpp.go:165 +0x3a
created by github.com/google/cups-connector/xmpp.newInternalXMPP
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/internal-xmpp.go:115 +0x9ec

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc208010840, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010840, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080107e0, 0xc208178000, 0x1000, 0x1000, 0x0, 0x7f062da28dd8, 0xc20837b4f0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c078, 0xc208178000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20803d6b0, 0x7f062da2a668, 0xc20802c078, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208176000, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208176000, 0xc208179000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f062da2f480, 0xc208176000, 0xc2080a4268, 0xc208179000, 0x1000, 0x1000, 0x70cc40, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20837d900, 0xc208179000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208309c80)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208309c80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080a4210)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc2080a4210)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 16 [select]:
github.com/google/cups-connector/xmpp.(*internalXMPP).pingPeriodically(0xc2083d96d0, 0x37e11d600, 0xf224d4a00, 0xc2083e6a80)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/internal-xmpp.go:139 +0x31a
created by github.com/google/cups-connector/xmpp.newInternalXMPP
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/internal-xmpp.go:116 +0xa2a

goroutine 18 [select]:
github.com/google/cups-connector/xmpp.(*XMPP).keepXMPPAlive(0xc208088100)
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/xmpp.go:128 +0x2d2
created by github.com/google/cups-connector/xmpp.(*XMPP).startXMPP
	/tmp/buildd/google-cloudprint-tools-2015/src/github.com/google/cups-connector/xmpp/xmpp.go:113 +0x2f1

goroutine 310 [IO wait]:
net.(*pollDesc).Wait(0xc208410c30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208410c30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208410bd0, 0xc208552000, 0x1000, 0x1000, 0x0, 0x7f062da28dd8, 0xc2081b82c8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802d3d8, 0xc208552000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20868db60, 0x7f062da2a668, 0xc20802d3d8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2085798c0, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2085798c0, 0xc2088f7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f062da2f480, 0xc2085798c0, 0xc208412478, 0xc2088f7000, 0x1000, 0x1000, 0x70cc40, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208598960, 0xc2088f7000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20859ad80)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20859ad80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208412420)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 250 [IO wait]:
net.(*pollDesc).Wait(0xc208411db0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208411db0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208411d50, 0xc20866a000, 0x1000, 0x1000, 0x0, 0x7f062da28dd8, 0xc2086c7508)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802cef8, 0xc20866a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20865a8a0, 0x7f062da2a668, 0xc20802cef8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208430840, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208430840, 0xc2088a7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f062da2f480, 0xc208430840, 0xc20850a058, 0xc2088a7000, 0x1000, 0x1000, 0x70cc40, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2085985a0, 0xc2088a7000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20859a240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20859a240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20850a000)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 251 [select]:
net/http.(*persistConn).writeLoop(0xc20850a000)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 311 [select]:
net/http.(*persistConn).writeLoop(0xc208412420)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

**Comment by jacobmarble** [comment]
@akorobkin can you try the most recent release? 31-jul is quite old at this point.

I have found where the error is coming from, but still not sure why it's happening.
