### ISSUE TITLE
OpenWRT/MIPS support

### ISSUE THREAD

**Issue by senposage** [google/cups-connector#119]
is it possible to compile this for OpenWRT/MIPS

**Comment by jacobmarble** [comment]
It should, and you're welcomed to try. Don't try to cross-compile from your x86 machine, as we use C libraries. You'll have to compile Go on the OpenWRT/MIPS device, then compile the connector. Steps here (see the footnote at the bottom about compiling Go):
https://github.com/google/cups-connector/wiki/Build-from-source
