### ISSUE TITLE
disk space and fail to parse PPD

### ISSUE THREAD

**Issue by dmonty2** [google/cups-connector#120]
Two issues, not sure if they are related or not.

=== disk space issue ===
/tmp is filling up with /tmp/cups-connector-ppd-123456789 files
It appears these are duplicate files.   A new file is created each minute.
-rw-------  1 root         root          43803 Oct 27 08:20 cups-connector-ppd-237478287
-rw-------  1 root         root          43803 Oct 27 08:21 cups-connector-ppd-078986146
-rw-------  1 root         root          43803 Oct 27 08:22 cups-connector-ppd-932744857
-rw-------  1 root         root          43803 Oct 27 08:23 cups-connector-ppd-304072996
-rw-------  1 root         root          43803 Oct 27 08:24 cups-connector-ppd-200075827
-rw-------  1 root         root          43803 Oct 27 08:25 cups-connector-ppd-674244086
-rw-------  1 root         root          43803 Oct 27 08:26 cups-connector-ppd-556372701
-rw-------  1 root         root          43803 Oct 27 08:27 cups-connector-ppd-924804760
-rw-------  1 root         root          43803 Oct 27 08:28 cups-connector-ppd-802517783
-rw-------  1 root         root          43803 Oct 27 08:29 cups-connector-ppd-622685578
-rw-------  1 root         root          43803 Oct 27 08:30 cups-connector-ppd-167352673
-rw-------  1 root         root          43803 Oct 27 08:31 cups-connector-ppd-776080716
-rw-------  1 root         root          43803 Oct 27 08:32 cups-connector-ppd-072686139
-rw-------  1 root         root          43803 Oct 27 08:33 cups-connector-ppd-349696094
-rw-------  1 root         root          43803 Oct 27 08:34 cups-connector-ppd-375546405

=== log issue ===
cups-connector logs have allot of repeated lines also repeating each minute:

E1027 08:26:17.999086    8429 cups.go:278] Failed to parse PPD
E1027 08:27:18.371375    8429 cups.go:278] Failed to parse PPD
E1027 08:28:18.731132    8429 cups.go:278] Failed to parse PPD
E1027 08:29:19.028848    8429 cups.go:278] Failed to parse PPD
E1027 08:30:19.344764    8429 cups.go:278] Failed to parse PPD
E1027 08:31:19.699839    8429 cups.go:278] Failed to parse PPD
E1027 08:32:20.063545    8429 cups.go:278] Failed to parse PPD
E1027 08:33:20.382371    8429 cups.go:278] Failed to parse PPD
E1027 08:34:20.743673    8429 cups.go:278] Failed to parse PPD
E1027 08:35:21.104577    8429 cups.go:278] Failed to parse PPD
E1027 08:36:21.463410    8429 cups.go:278] Failed to parse PPD

**Comment by dmonty2** [comment]
Running cupstestppd /tmp/cups-connector-ppd-539821471
      **FAIL**  BAD PSVersion - not "(string) int".
                REF: Pages 62-64, section 5.3.

grep PSVers /tmp/cups-connector-ppd-539821471 
*PSVersion: "(3010)"

I re-installed the driver/ppd for the printer and it fixed the PSVersion as well as the Failed to parse PPD errors.  Closing the ticket - in case someone else has these issues.

**Comment by jacobmarble** [comment]
I'm re-opening this because the cached PPD file should be deleted, even if it fails to parse. I'll close it when I submit a fix for that.
