### ISSUE TITLE
Use default values for missing config values

### ISSUE THREAD

**Issue by agoode** [google/cups-connector#125]
In distribution packaging scenarios (such as Fedora), cups-connector will be upgraded without a chance to update its config file.

At some point (perhaps 1.0) the config file should be guaranteed to be forward-compatible in all cases. It probably is still a fine idea to allow for a config file upgrade, to show new potential options, but it should not be necessary.

**Comment by jay0lee** [comment]
Why couldn't post install scripts be leveraged to call the upgrade? Both .rpm and .deb allow for them I believe. See:

https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s04s05.html

**Comment by agoode** [comment]
That is another option, as long as
 * it is safe to run the config upgrade multiple times without harm
 * the upgrade will succeed regardless of how old the config file is

**Comment by jacobmarble** [comment]
I cannot commit to eliminating the need to upgrade the config file forever, but future changes should be far fewer, as there aren't a lot of features to add any more. There is one config option that I would like to rename, and I can implement that before v1.0. Still, the config upgrade will take care of the rename.

Both of your conditions are already met.

**Comment by agoode** [comment]
Ok. I guess it does seem a little strange to me that all of the config fields are required in the file. I would expect that missing fields get set to the default.

Would you be open to changing this? It is a generalization of the empty config file case.

**Comment by jacobmarble** [comment]
Yes, I can switch to using default values for missing values.

**Comment by jay0lee** [comment]
My concern with this is if you are missing "enable_cloud_print" or
something similar which is relatively new, it's non-obvious why only local
printing works.

Jay

On Tue, Nov 10, 2015, 11:50 AM Jacob Marble <notifications@github.com>
wrote:

> Yes, I can switch to using default values for missing values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cups-connector/issues/125#issuecomment-155483775>
> .
>
-- 

Jay Lee

**Comment by jacobmarble** [comment]
How about a log+stderr message to notify the user? This is already true for missing config file.
