### ISSUE TITLE
Error on wiki 'configuration' page

### ISSUE THREAD

**Issue by lycurgus** [google/cups-connector#128]
The wiki ['Configuration' page](https://github.com/google/cups-connector/wiki/Configuration) lists the command for generating a default config file as `gcp-cups-connector-util -init`. Running this command yields a message 'Incorrect usage', and the usage text. Running instead `gcp-cups-connector-util init` (no hyphen) generates no error message and begins the prompt to generate a config file. It seems the wiki is therefore in error.

I had [edited the page](https://github.com/google/cups-connector/wiki/Configuration/054e61224b448f1ee70a60794c76ff49de59f0d6), but [it got changed back](https://github.com/google/cups-connector/wiki/Configuration/80414b882d3669f89886ffec9ad25260119f6410). Rather than changing it yet again and getting into a petty back-and-forth, I figured it best to raise an issue - is there some platform-dependent difference in the arguments that `gcp-cups-connector-util` takes that I might be unaware of? Or does the wiki page simply need a note stating that the hyphenless version is indeed correct?

**Comment by jacobmarble** [comment]
The behavior changed in #122, and I haven't made a new release yet. Since you're building from source, you get the bleeding edge.

The person who reverted your change is using a released version. I'll add a note about this to the wiki page.
