### ISSUE TITLE
malloc(): smallbin double linked list corrupted

### ISSUE THREAD

**Issue by akorobkin** [google/cups-connector#13]
Found in the stderr log today:

E0602 03:39:39.404833   29875 printermanager.go:506] https://www.google.com/cloudprint/control call failed: Unknown job id.
E0602 03:39:39.868477   29875 printermanager.go:506] https://www.google.com/cloudprint/control call failed: Unknown job id.
E0602 03:40:43.846538   29875 printermanager.go:506] https://www.google.com/cloudprint/control call failed: Unknown job id.
*** glibc detected *** /opt/cloudprint/bin/connector: malloc(): smallbin double linked list corrupted: 0x0000000001b75710 ***

connector.INFO around the same time:
I0602 03:38:47.883820   29875 printermanager.go:433] Received job 0df022cb-3d66-448b-df52-07ea77ed24c6
I0602 03:38:48.165975   29875 printermanager.go:410] Downloaded job 0df022cb-3d66-448b-df52-07ea77ed24c6 in 186.474687ms
I0602 03:38:48.532184   29875 printermanager.go:470] Submitted GCP job 0df022cb-3d66-448b-df52-07ea77ed24c6 as CUPS job 508654
I0602 03:38:50.380358   29875 printermanager.go:508] Job 0df022cb-3d66-448b-df52-07ea77ed24c6 status is now: PROCESSING/IN_PROGRESS
I0602 03:38:52.047503   29875 printermanager.go:508] Job 0df022cb-3d66-448b-df52-07ea77ed24c6 status is now: COMPLETED/DONE
I0602 03:39:20.035050   29875 printermanager.go:433] Received job 6b2d3403-6d5b-228f-f8b2-b49e920a1d46
I0602 03:39:20.310799   29875 printermanager.go:410] Downloaded job 6b2d3403-6d5b-228f-f8b2-b49e920a1d46 in 187.653548ms
I0602 03:39:20.686809   29875 printermanager.go:470] Submitted GCP job 6b2d3403-6d5b-228f-f8b2-b49e920a1d46 as CUPS job 508657
I0602 03:39:22.247684   29875 printermanager.go:508] Job 6b2d3403-6d5b-228f-f8b2-b49e920a1d46 status is now: PROCESSING/IN_PROGRESS
I0602 03:39:23.219372   29875 printermanager.go:508] Job 6b2d3403-6d5b-228f-f8b2-b49e920a1d46 status is now: COMPLETED/DONE
E0602 03:39:39.404833   29875 printermanager.go:506] https://www.google.com/cloudprint/control call failed: Unknown job id.
I0602 03:39:39.416239   29875 printermanager.go:508] Job b7fa2e06-fe30-77ee-367a-f3b8537f59f1 status is now: COMPLETED/DONE
E0602 03:39:39.868477   29875 printermanager.go:506] https://www.google.com/cloudprint/control call failed: Unknown job id.
I0602 03:39:39.868516   29875 printermanager.go:508] Job 2915843f-240a-63da-beef-9730ee3ef8cc status is now: PROCESSING/IN_PROGRESS
E0602 03:40:43.846538   29875 printermanager.go:506] https://www.google.com/cloudprint/control call failed: Unknown job id.
I0602 03:40:43.846586   29875 printermanager.go:508] Job 2915843f-240a-63da-beef-9730ee3ef8cc status is now: COMPLETED/DONE
I0602 03:40:46.885124   29875 printermanager.go:433] Received job 793204cf-8041-a78f-c1c2-4976f25563a4
I0602 03:40:47.179649   29875 printermanager.go:410] Downloaded job 793204cf-8041-a78f-c1c2-4976f25563a4 in 202.525614ms

**Comment by jacobmarble** [comment]
@akorobkin have you seen this behavior lately? I suspect that it is fixed.
