### ISSUE TITLE
Use IPP commands to fetch PPDs without temporary files

### ISSUE THREAD

**Issue by agoode** [google/cups-connector#134]
https://www.cups.org/documentation.php/doc-2.1/api-httpipp.html#ASYNCHRONOUS_REQUEST_PROCESSING

`ippNewRequest(CUPS_GET_PPD)`
`cupsSendRequest`
`cupsGetResponse`
`cupsReadResponseData`

You can use `If-Modified-Since` (as `HTTP_FIELD_IF_MODIFIED_SINCE` in cups/http.h) for cache invalidation.

**Comment by jacobmarble** [comment]
This will simplify things in /cups quite a bit.

**Comment by jacobmarble** [comment]
Here's one reason I like `cupsGetPPD3`. If the CUPS server hostname is `localhost` or `/anything` (Unix socket) then there is no IPP request. I optimized for this by only creating a new connection when necessary.

https://github.com/google/cups-connector/blob/master/cups/core.go#L154
https://github.com/google/cups-connector/blob/master/cups/core.go#L74
https://opensource.apple.com/source/cups/cups-408.2/cups/cups/util.c (look for comment "See if the PPD file is available locally")

This way, we save a bunch of connection open/close on 99% of users' machines. This is particularly helpful on larger CUPS servers (200-400 printers). Temporary files linger for the lifetime of the connector.

We could do this filesystem check ourselves. I'll think about it, but it's low on my priorities for now.

**Comment by jacobmarble** [comment]
I can continue to use cupsGetPPD3, delete the returned PPD files, and retain the modtime parameter.
https://www.cups.org/pipermail/cups/2015-November/027293.html
