### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by jacobmarble** [google/cups-connector#136]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803413

**Comment by jacobmarble** [comment]
The package has been accepted to Debian unstable (see bug link).

Big thanks to @cklin

**Comment by jay0lee** [comment]
woot!

**Comment by jacobmarble** [comment]
https://packages.debian.org/sid/google-cloud-print-connector

**Comment by leizleiz** [comment]
Any plans to submit packages for other architectures?

**Comment by jacobmarble** [comment]
Yes, I need to find out what's wrong with the others.

**Comment by jacobmarble** [comment]
Further updates will belong to the Debian tracker
