### ISSUE TITLE
Centos 7.x Openssl Incompatibility

### ISSUE THREAD

**Issue by dirtyworks** [google/cups-connector#142]
./gcp-cups-connector: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

The error is from the downloaded binaries.

CentOS 7.x has no openssl package 1.0.0.  
It does have:
openssl098e-0.9.8e-29.el7.centos.2.x86_64
openssl-libs-1.0.1e-42.el7.9.x86_64
openssl-libs-1.0.1e-42.el7.9.i686
openssl-1.0.1e-42.el7.9.x86_64
openssl-devel-1.0.1e-42.el7.9.x86_64

I tried a symlink trick and the error changes.  
gcp-cups-connector: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by gcp-cups-connector)
I'm entirely new to go code, so I'm no use.

**Comment by jacobmarble** [comment]
This is a known issue on Fedora, RHEL and CentOS. The solution is to [install from source](https://github.com/google/cups-connector/wiki/Build-from-source). You should at least try the instructions. Lots of people have muddled through.

**Comment by dirtyworks** [comment]
Yeah, I RTFM. Installing from source isn't working either.  That's not your issue though.

**Comment by jacobmarble** [comment]
Any progress @dirtyworks ?

**Comment by jacobmarble** [comment]
Today's release includes binaries built on CentOS 7. Please re-open this issue if that doesn't work for you.
