### ISSUE TITLE
1648 printermanager.go:234] Failed to share printer 

### ISSUE THREAD

**Issue by chrisville** [google/cups-connector#143]
Hi,

I'm kindly requesting help with a problem. I have a Linux server running CUPs for my print server. It is loading fine to Google Cloud Print. I can then share my printers with now problem. However, if I reboot the server and start the cloud service again I get this error: 1648 printermanager.go:234] Failed to share printer ResourceCenter_HP_Color_LaserJet_CP3525: https://www.google.com/cloudprint/share call failed: Failed to share the printer - and all my old printers are gray (offline) on google cloud print.  Pretty much, It creates new copies of the printers and none of the sharing I did remains.

Any help will be highly appreciated.

Regards,
-Chris

**Comment by jacobmarble** [comment]
I don't have any guesses so far. Please send the log file from before reboot, when the printer is registered successfully, an the subsequent log file from after reboot, when sharing fails.

After that, please describe what happens when you disable sharing.

**Comment by chrisville** [comment]
Thank you for your reply Jacob. Is it the /tmp/connector.INFO? thanks again!

Regards,
-Chris

**Comment by jacobmarble** [comment]
Yes. That's actually a link, but you can easily make a copy before reboot, then another copy after the failure.

**Comment by chrisville** [comment]
yes yes, just wanted to make sure I was aiming to the right file. I will reproduce the issue and collect the logs for and post them. Thank you for the follow up Jacob!.

**Comment by jacobmarble** [comment]
Hi, any progress here?

**Comment by chrisville** [comment]
Hi, thank you for following up. We have had a very busy week and could not collect the logs yet but I will have them tomorrow. Thank you again. Regards,

-Chris

**Comment by chrisville** [comment]
Hi Jacob,

I sent the logs to your email. Thank you!

**Comment by jacobmarble** [comment]
How many times have you initialized a config file with your Google account?

I think automatic sharing might have something to do with this problem. The OAuth token is different for sharing; the rest of the Cloud Print API calls use a "robot" account token, while sharing uses the user's own account.

**Comment by Gi11i4m** [comment]
Hello,

I also have this problem with my Raspberry Pi 2 running the CUPS connector on Raspbian. Every time a reboot happens the printers registered on the connector are added to GCP again and I have to share them again too.

Expected behaviour would be that the printers would be marked offline on GCP when the server is powered down, and online when the server is up again.

It's a recurring and annoying problem and I'm happy to provide logs as soon as I can if needed.
