### ISSUE TITLE
Release of rpi-wheezy version seems to be mislabeled - segfault

### ISSUE THREAD

**Issue by nivekuil** [google/cups-connector#145]
Output from a raspberry pi on raspbian (wheezy):
```
$ cat /etc/debian_version 
7.8

$ cat /proc/version 
Linux version 4.1.7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #817 PREEMPT Sat Sep 19 15:25:36 BST 2015

$ curl -sL https://github.com/google/cups-connector/releases/download/2015.10.05/gcp-cups-connector-rpi-wheezy-2015.10.05.tar.gz | tar xvz

$ ./cups-connector/gcp-cups-connector
E1205 22:12:48.381907   19189 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version 2015.10.05-linux
Google Cloud Print CUPS Connector version 2015.10.05-linux
Segmentation fault
```

It works properly with the `jessie` version of the 10.05 release. I also tried the previous two releases, and both had a segmentation fault. I see that https://github.com/google/cups-connector/issues/100 had the same problem, so maybe an older version got mislabeled.

**Comment by jacobmarble** [comment]
I just tried the wheezy release binary on my own RPi B+, without problem. What hardware are you using?

**Comment by jacobmarble** [comment]
Also, your console output matches mine exactly, except for the error. I'm now more suspicious of hardware difference.

**Comment by jacobmarble** [comment]
Please copy-paste the output from `uname -a`

**Comment by nivekuil** [comment]
```
$ uname -a
Linux hostname 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 000f
Serial          : 00000000ad998149
```

**Comment by jacobmarble** [comment]
Thanks for the `/proc/cpuinfo` as well. We differ in the Revision field. I compiled that binary on a RPi whose Revision value 0010, a B+. We're reaching the limits of my hardware know-how.

Email me at jacobmarble@google.com so that I can send you a binary compiled on a 000e board. Shot in the dark.

**Comment by jacobmarble** [comment]
I just tried the latest Jessie release on that 000e board. No problems. I'll try some more things tomorrow.

**Comment by jacobmarble** [comment]
I sent you a freshly-compiled-on-wheezy 000e connector. Let me know if that works.

My colleague here happened to have a 000f board collecting dust. I dropped my wheezy SD card in, and the 2015.10.05 binaries work fine.

**Comment by nivekuil** [comment]
It's likely something on my end then. The version you sent me couldn't find "libnetsnmp.so.15". I symlinked the libnetsnmp on my system (libnetsnmp.so.30) to /usr/lib/libnetsnmp.so.15, and it still had a segfault. Here's as far as it gets in gdb, for whatever it's worth:
```
$ gdb ./gcp-cups-connector
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /tmp/cups-connector.2/gcp-cups-connector...run
done.
warning: Missing auto-load scripts referenced in section .debug_gdb_scripts
of file /tmp/cups-connector.2/gcp-cups-connector
Use `info auto-load-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /tmp/cups-connector.2/gcp-cups-connector 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0xb6965600 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) continue
Continuing.
Cannot access memory at address 0x0

Program received signal SIGILL, Illegal instruction.
0xb6965608 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) continue
Continuing.
Cannot access memory at address 0x0
[New Thread 0xb656c440 (LWP 28567)]
[New Thread 0xb5d2c440 (LWP 28568)]
[New Thread 0xb53ff440 (LWP 28569)]
Google Cloud Print CUPS Connector version DEV-linux

Program received signal SIGSEGV, Segmentation fault.
0xb6f76808 in httpConnectEncrypt () from /usr/lib/arm-linux-gnueabihf/libcups.so.2
```
I'll try a clean install of raspbian on my pi as well. Feel free to close this issue if you feel that it's resolved.

**Comment by jacobmarble** [comment]
There's your problem. libnetsnmp.so.15 isn't the same as libnetsnmp.so.30.
The 2015.10.05 binary has libnetsnmp statically linked. The binary I sent
has that library dynamically linked.

When was the last time you ran apt-get update and apt-get upgrade?

**Comment by jacobmarble** [comment]
I need to change what I just said. libnetsnmp.so.15 belongs to libsnmp15, the package that belongs to wheezy.
https://packages.debian.org/wheezy/libsnmp15

libsnmp30 lives in jessie, but not wheezy. You have a newer version of the package, but you're using wheezy; why? I downloaded my image from here:
https://www.raspberrypi.org/downloads/raspbian/

Where did you get yours?

**Comment by jacobmarble** [comment]
Also, what does `/etc/apt/sources.list` contain? Here's mine:
```
$ cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ wheezy main contrib non-free rpi
```

**Comment by nivekuil** [comment]
```
$ cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian wheezy main contrib non-free rpi
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
```
Looks like apt is pulling from the jessie repositories by default. I can't speak as to why, since I am not the owner (and apt-get upgrade has not been run in a while), but it's my mistake for not catching this sooner. The problem was that while the rest of the system was on wheezy, when I `apt-get install`ed libsnmp it pulled the jessie version, which was enough to break the wheezy binary.

**Comment by jacobmarble** [comment]
OK, I'm considering this a "lesson learned", and I'll refer to it as needed in the future. If you learn why this happened (might be the side effect of some package or other WTF), please let me know.
