### ISSUE TITLE
Not able to register printer on rpi with osmc

### ISSUE THREAD

**Issue by pmishev** [google/cups-connector#146]
I'm running an osmc distro on a raspberry pi (which is based on debian jessie I believe).
I run the connector:
```
osmc@osmc:~/cups-connector$ ./gcp-cups-connector
E1207 00:55:53.597552     682 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version 2015.10.05-linux
Google Cloud Print CUPS Connector version 2015.10.05-linux
E1207 00:55:54.690892     682 gcp-cups-connector.go:148] Ready to rock in local-only mode
```

And in `chrome://devices/` I can see my cups printer show up. However, when I try to register it, I get an error: `An error has occurred. Please check your printer and try again`.

Listening with tshark like this `$ sudo tshark -Y 'http.request or http.response'`, gives me the following output:
```
606  38.098091 192.168.0.15 -> 192.168.0.5  HTTP 469 GET /privet/info HTTP/1.1 
608  38.115429  192.168.0.5 -> 192.168.0.15 HTTP 1114 HTTP/1.1 200 OK  (text/plain)
610  38.124695 192.168.0.15 -> 192.168.0.5  HTTP 563 POST /privet/register?action=start&user=mymail%40gmail.com HTTP/1.1 
611  38.127324  192.168.0.5 -> 192.168.0.15 HTTP 242 HTTP/1.1 404 Not Found  (text/plain)
```

I do not have any custom configuration for the connector. Am I missing something or could it be a problem with the connector?

**Comment by jacobmarble** [comment]
Chrome has a bug. The printer doesn't need to be registered; the connector handles that automatically. Try to print something, it should work fine.

**Comment by pmishev** [comment]
You are right. It turns out the gcp-cups-connector is not needed at all. Why I tried to print a doc from google docs, it detected the printer in 'local destinations' and allowed me to register it for google cloud print. Thanks!

I wonder what's the purpose of the gcp-cups-connector script in that case?

**Comment by jacobmarble** [comment]
I'm glad you got printing to work.

Re the purpose of gcp-cups-connector, you have left out a lot of details, but here's a guess. If your printer is [Cloud Ready](https://www.google.com/cloudprint/learn/printers.html) then you don't need the connector, and that sounds like what happened to you.
