### ISSUE TITLE
Support mostly-empty config file with comments

### ISSUE THREAD

**Issue by agoode** [google/cups-connector#148]
I would like to ship a minimal config file on Fedora that only specifies overrides to defaults.

The config file format should also allow for comments, so that config options can be documented in place, and the defaults could be present but commented out. Currently, JSON does not allow this.

Probably something INI-style would be good. This is a common format on Linux for configs. I am not sure which library to use, but there are several.

If LGPL code is ok, then http://gopkg.in/v2/yaml might be ok for YAML.

There is also https://github.com/spf13/viper/ for reading and writing several formats, but it might be too complex.

**Comment by agoode** [comment]
Here is one INI reader:
https://gopkg.in/gcfg.v1

**Comment by agoode** [comment]
I think this is mostly done now? Defaults work. Comments would be nice, but are not necessary. I am happy with the setup as it is now.

**Comment by jacobmarble** [comment]
Yep.
