### ISSUE TITLE
Printer in "local-only mode" insted of working in "proxy and local mode", why?

### ISSUE THREAD

**Issue by LateWiksi** [google/cups-connector#149]
Hi all!

CUPS Connector works sometimes just fine, but sometimes "local-only". For an example today I have received multiple times notification "Ready to rock in local-only mode". Killing the process waiting 30min and restarting the CUPS Connector and the result is same. While printer is "local-only mode" it's not online on Google Cloud Print https://www.google.com/cloudprint#printers

Log:
I [11/Dec/2015:15:39:34 +0200] No config file was found, so using defaults
I [11/Dec/2015:15:39:34 +0200] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
I [11/Dec/2015:15:39:34 +0200] connected to CUPS server /var/run/cups/cups.sock:631 encrypting REQUIRED
I [11/Dec/2015:15:39:34 +0200] Local printing enabled (Avahi client is running).
I [11/Dec/2015:15:39:34 +0200] Synchronizing printers, stand by
I [11/Dec/2015:15:39:35 +0200] Finished synchronizing 1 printers
I [11/Dec/2015:15:39:35 +0200] [Printer HP_Color_LaserJet_1600] Registered locally
I [11/Dec/2015:15:39:35 +0200] Ready to rock in local-only mode
Ready to rock in local-only mode

How ever, waiting a couple of hours and restarted CUPS connector normally and Google Cloud Print started to work. Received "Ready to rock as proxy 'raspi-print-server' and in local mode" notification.

Any ideas why CUPS Connector doesn't always allow me to run CUPS Connector in "proxy mode" as it should?

Device: Raspberry Pi model B+
OS: Rasbian 8.0 (Debian Jessie)
Location: /home/pi/cups-connector/
Running on background as pi with command /gcp-cups-connector --log-to-console 
Iptables settings: ALLOW ALL
Cable modem firewall is also set to ALLOW ALL traffic to Raspberry Pi.

CUPS Connector start automatically on Raspberry Pi boot /etc/rc.local entry set.

Any ideas? I've tried to also run as root, doesn't have any effort.

**Comment by jay0lee** [comment]
Try adding:

-config-filename /path/to/your/config.json

When starting the connector.

Jay

**Comment by LateWiksi** [comment]
Hey! Thank you jay0lee! 

Adding a full path to -config-filename solved the problem!

This works:
./gcp-cups-connector --log-to-console -config-filename /home/pi/cups-connector/gcp-cups-connector.config.json

This doesn't:
./gcp-cups-connector --log-to-console -config-filename gcp-cups-connector.config.json

I guess the reason is I haven't been starting gcp-cups-connector from the same directory where config file is located. For an example if I tried to start CUPS connector from /home with command /home/pi/cups-connector/gcp-cups-connector --log-to-console -config-filename gcp-cups-connector.config.json it haven't worked. Adding a full path for config fixed this.

Thank you once again and have a nice weekend! :)
