### ISSUE TITLE
Can't add printer

### ISSUE THREAD

**Issue by Rudloff** [google/cups-connector#156]
I have a CUPS server on a Raspberry Pi with a NRG DSm622 printer.
The connector seems to run correctly:
```
E1218 15:29:39.478513    5967 gcp-cups-connector.go:34] Google Cloud Print CUPS Connector version 2015.10.05-linux
Google Cloud Print CUPS Connector version 2015.10.05-linux
E1218 15:29:40.389836    5967 gcp-cups-connector.go:148] Ready to rock in local-only mode
Ready to rock in local-only mode
```

But when I try to add the printer on `chrome://devices`, it gets stuck on the "You must confirm registration on the printer, check it now" message.

**Comment by jacobmarble** [comment]
No need to register the printer. Just print to it.

Chrome sees local-only printers as needing to be registered, but it shouldn't. It's a bug, related to https://crbug.com/540847

When I click "register" at chrome://devices the attached modal dialog appears. Apparently this is different for you. What platform are you running Chrome on?

![screen shot 2015-12-18 at 9 26 57 am](https://cloud.githubusercontent.com/assets/622263/11902834/88a8aace-a569-11e5-99ed-37b3e70e5792.png)

**Comment by Rudloff** [comment]
I get this (in French, sorry):
![screenshot - 18122015 - 18 42 17](https://cloud.githubusercontent.com/assets/840125/11903112/2936acc8-a5b7-11e5-8194-28b8e44f3a06.png)
It is the same on Ubuntu and Mac OS.

But you're right, I can print to it, I thought it needed to be registered first.

**Comment by jacobmarble** [comment]
Alright, please ignore the Chrome bug. Or better, add a comment to that crbug.com link.

**Comment by ask-compu** [comment]
i'm having a similar issue, i used to have a local hp printer (hplip driver in cups) printer set up with ubuntu and it worked fine until today i noticed it was no longer working and cloud print was saying it had been offline for over a month (i don't print very often), so i deleted it and tried to re add it but chrome just gets stuck here
![screenshot](https://i.imgur.com/yvEv40k.png)

**Comment by RehxFnek** [comment]
thank

**Comment by RehxFnek** [comment]
thank you!
