### ISSUE TITLE
Show CUPS server connect info on failure

### ISSUE THREAD

**Issue by jacobmarble** [google/cups-connector#163]
#158 for context. Before the connector attempts to connect to a CUPS server, it should report where it is trying to connect to. This log entry should be adjusted:
```
connected to CUPS server /var/run/cups/cups.sock:631 encrypting REQUIRED
```

**Comment by adjobscc-del** [comment]
> #158 for context. Before the connector attempts to connect to a CUPS server, it should report where it is trying to connect to. This log entry should be adjusted:
> 
> ```
> connected to CUPS server /var/run/cups/cups.sock:631 encrypting REQUIRED
> ```
>
