### ISSUE TITLE
Systemctl Failed

### ISSUE THREAD

**Issue by compil3** [google/cups-connector#168]
I don't understand what could be causing this
`sudo systemctl enable gcp`
`Failed to execute operation: Bad message`

Any ideas?  This is on a RPI using Jessie

**Comment by Loran425** [comment]
@compil3 
I had the same problem.
Make sure that you do not include the quotation ```'``` or the function ```printf``` in the gcp.service file.
If you are following the wiki example it should look like this.
```bash
[Unit]
Description=Google Cloud Print CUPS Connector
After=printer.target network.target multi-user.target

[Service]
ExecStart=/opt/gcp_cups_connector/gcp-cups-connector -config-filename /etc/gcp_cups_connector/gcp-cups-connector.config.json
Restart=on-abort
User=gcp
Group=gcp

[Install]
WantedBy=multi-user.target
```

**Comment by Doc91b** [comment]
I also had to remove the following from the last line:

`' > gcp.service`

**Comment by agoode** [comment]
For now, try using the latest version of the systemd unit file here:
https://github.com/google/cups-connector/wiki/Run-Connector-Automatically-on-Boot

Please reopen if there is still a problem.
