### ISSUE TITLE
Some paper size seems to be filtered out by the connector

### ISSUE THREAD

**Issue by ekacnet** [google/cups-connector#169]
I have an EPSON R360 printer, I'm using the PPD from EPSON.
I would like to print on 4x6 paper but in the list of available format there is no 4x6, when I try to print through linux directly (ie. through CUPS only) it's working fine I'm proposed with the 4x6 format.

**Comment by jacobmarble** [comment]
Please send your PPD file to me via email.
jacobmarble@google.com
