### ISSUE TITLE
gcp.service error 127

### ISSUE THREAD

**Issue by kahunamike** [google/cups-connector#179]
Was following the RPI Jessie instructions and ran into this error. Any ideas?

pi@raspberrypi:~ $ sudo systemctl status gcp
● gcp.service - Google Cloud Print CUPS Connector
   Loaded: loaded (/etc/systemd/system/gcp.service; enabled)
   Active: failed (Result: exit-code) since Mon 2016-02-01 04:11:11 UTC; 3s ago
  Process: 1427 ExecStart=/opt/gcp_cups_connector/gcp-cups-connector --config-filename /etc/gcp_cups_connector/gcp-cups-connector.config.json (code=exited, status=127)
 Main PID: 1427 (code=exited, status=127)

My gcp.service file looks like this: already corrected the --config-filename
----------------
[Unit]
Description=Google Cloud Print CUPS Connector
After=printer.target network.target multi-user.target

[Service]
ExecStart=/opt/gcp_cups_connector/gcp-cups-connector --config-filename /etc/gcp_cups_connector/gcp-cups-connector.config.json
Restart=on-abort
User=gcp
Group=gcp

[Install]
WantedBy=multi-user.target
-----------------

**Comment by do7slash** [comment]
what does the log show? usually it's /tmp/cups-connector

**Comment by kahunamike** [comment]
Doesn't look like there's a log file getting generated as I don't think it ever starts.

**Comment by atesanec** [comment]
You need to install libsnmp.so
sudo apt-get install libsnmp-dev

After that demon should start - helped me on Raspberry PI, Minibian OS

**Comment by jacobmarble** [comment]
Added libsnmp30 to the apt-get step on the RPi instructions.
