### ISSUE TITLE
Won't build on FreeBSD

### ISSUE THREAD

**Issue by swills** [google/cups-connector#186]
I tried to build this project on FreeBSD and after making what I thought were the necessary changes, it still won't link due to the lack of a bulkwalk function in net-snmp. I'm using net-snmp 5.7.3. I can provide the detailed changes and error messages if needed. Have you guys tried building with this version of net-snmp? Just thought I'd drop a note here instead of sending a patch first, based on what I read here: https://github.com/google/cups-connector/wiki/Build-from-source#get-ready

**Comment by jacobmarble** [comment]
I'm happy that you're trying the connector on FreeBSD. I recently made some changes to build tags that would give you some trouble, but you must have discovered those already.

I regularly test with Ubuntu 14.04, which uses NetSNMP 5.7.2, and the Debian package builds on testing and unstable without incident, those use NetSNMP 5.7.3.

I don't have a FreeBSD machine, and don't have bandwidth to set one up. Feel free to send a PR.

**Comment by jacobmarble** [comment]
Don't bother with that pull request. I'm going to remove the SNMP stuff right now.

**Comment by jacobmarble** [comment]
SNMP is gone now. Looking forward to your patch; happy to help with any other concerns.

**Comment by swills** [comment]
Thanks! I'm working on it now, but ran into an issue with the logging using systemd journal logging. Systemd doesn't exist on FreeBSD but as far as I can tell, the logging relies on the systemd journal logging and at the same time compiles on darwin (Mac OS X), so I'm a bit confused. Suggestions?

**Comment by jacobmarble** [comment]
Fixed in #199
