### ISSUE TITLE
Problems creating config json with gcp-connector-util init 

### ISSUE THREAD

**Issue by a-andreyev** [google/cups-connector#194]
Installed on Raspberry Pi 2 with ArchLinuxARM (with AUR) via this script:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gcp-cups-connector

Problems with creating init config file while writing to file:
```
[...]
Acquired OAuth credentials for robot account
open /home/username: is a directory
```

**Comment by a-andreyev** [comment]
sorry, everything is ok with the binary rpi package, so I should ask distro forum first.

**Comment by jacobmarble** [comment]
I'm running into the same issue. Must have missed something in the PR merges on Wednesday.
