### ISSUE TITLE
Just won't print.

### ISSUE THREAD

**Issue by martinshields** [google/cups-connector#197]
Just got it all setup up on my RPI jessie . Its a brothers printer connected to lan. Cups is  running .Gcp is running . I see the jobs completed  on the cups jobs page.  The printer shows up on all the chromebook and pc's. i even find it on the google cloud print page as "Printer is online and ready to print" But it just wont print. Hope you can point me in the right direction . The printer is working find with my mint box. but not when i use the local raspberry pi connection.

**Comment by kylemacfarlane** [comment]
I had a hard time getting a Brother printer to work with CUPS (it's a CUPS issue, not GCP).

I have a HL-L2365DW which is a part of the same family as the 2270, 2340, 2360, etc. Brother's CUPS drivers for these printers include closed source CUPS filters that are only compiled for x86 and don't work on the Raspberry Pi. When you try and print CUPS will say it's a success but actually the print will silently fail at the filter stage. If you try and install the .debs without the --force-all they will fail with an architecture error.

I found that using the driver for the 7050N that comes with CUPS works OK. It gives a reduced quality warning but the quality seems fine. However it is quite slow and will never reach the full 30ppm but that's always the case when you have to pass prints through a raster process.

I also tried taking the .ppd files out of Brother's cupswrapper .deb and merging with the 7050N's .ppd to create a better config and while I can get it to work it's super low quality. I'm sure someone could do it but for me it's too much time.

**Comment by masood13** [comment]
I have also a rpi jessie with a Brother DCP-7030. Works perfectly with CUPS on my local network, even when connected to GCP via a chrome browser online on a pc in my network. But it just doesn't print when I try to use the gcp-connector (when I take that pc offline). I used http://www.openprinting.org/driver/brlaser as a driver for my printer when I added it in CUPS administration. 

Do you know where I can check for some logs to get a clue why it doesn't work?

Thanks.

**Comment by martinshields** [comment]
I got it to work. I have the Brother DCP-7065DN  and kylemacfarlane was right. It was drivers. If you have a brothers printer you should try this [https://github.com/pdewacht/brlaser](url) . It prints faster too . As usual github saved my ass. Thanks guys

**Comment by martinshields** [comment]
logs are in /tmp/cup-connecter. and make sure you pick the brlaser drivers in the cups admin

**Comment by agoode** [comment]
Sorry about the printing problems. If CUPS is not working, the GCP connector won't work either. Hopefully you're having better luck.
