### ISSUE TITLE
Upstart doesn't work

### ISSUE THREAD

**Issue by ace214** [google/cups-connector#202]
Hi-

I'm trying to get this running on a Ubuntu 14.04 server. I'm using the Upstart script posted on the Wiki.

I'm getting the following log:
I [14/Mar/2016:12:37:28 -0400] Google Cloud Print CUPS Connector version 2016.02.01-linux
X [14/Mar/2016:12:37:28 -0400] While starting XMPP, failed to get access token (password): Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on [::1]:53: read udp [::1]:53315->[::1]:53: read: connection refused

When I run it directly from the console, it works fine.

Would appreciate any help.

**Comment by jacobmarble** [comment]
I'm not familiar with upstart. It looks like the network connection hasn't come up yet, so try to add something like "sleep 30" before the connector starts.

**Comment by agoode** [comment]
Can you verify you have the upstart config at https://github.com/google/cups-connector/wiki/Run-Connector-Automatically-on-Boot ?

The old wiki page "upstart script" wasn't an upstart script at all, so I deleted it.

Please reopen this issue if you still have problems.
