### ISSUE TITLE
Printing large (~30 pages) docx or pdf results in an error

### ISSUE THREAD

**Issue by abalnflx** [google/cups-connector#205]
When printing a large job docx or pdf from a windows machine (7 or 10) using the Cloud Print (https://tools.google.com/dlpage/cloudprintdriver) results in the following error (this gets printed out int he middle of the print job and stops after) 

ERROR:
invalidfont
OFFENDING COMMAND:
awidthshow
STACK:
g
0
0
32
0
0
-mark-
-mark-
-mark-

The document prints just fine from a another platfomr (ubuntu 14.04 and osx 10.11.3) 

Not sure if its a cloud print thing or a chrome thing.

Thanks!

**Comment by jacobmarble** [comment]
This looks like an incompatibility between the PDF format and CUPS. The
Connector doesn't change anything about the PDF it receives from Cloud
Print, just hands it to CUPS.

You might try to isolate the PDF, then print it directly on the CUPS
server, see if the same problem happens.

**Comment by agoode** [comment]
The Cloud Print Driver might be producing bad output.

Try filing a bug here:
https://bugs.chromium.org/p/chromium/issues/entry?template=Defect%20report%20from%20user&labels=Cr-Services-CloudPrint,OS-Windows,Cr-Services-CloudPrint-Driver
