### ISSUE TITLE
Failed to initialize robot account: 500 Internal Server Error

### ISSUE THREAD

**Issue by zipitup** [google/cups-connector#212]
I am installing this on Debian and after answering all the init questions, I entered the code on www.google.com/device and then got the:
"Failed to initialize robot account: 500 Internal Server Error"

Anyone have any idea what's wrong?

Thanks.

**Comment by sicklittlemonkey** [comment]
Yes, this must be a server-side problem. I've had the same thing trying to test the Windows port, issue #206. The Windows gcp-cups-connector-util init has never worked for me.

Interestingly I also had the same problem the first time I tried to use the Linux gcp-cups-connector-util -init from gcp-cups-connector-linux-amd64-2015.10.05.tar.gz on Wed, Dec 16 2015.

Then the next time (on the same day) it ran fine.

Today using the same Linux binary I get the same error I got back in December.

Request:
```
GET https://www.google.com/cloudprint/createrobot?oauth_client_id=539833558011-35iq8btpgas80nrs3o7mv99hm95d4dv6.apps.googleusercontent.com HTTP/1.1
Host: www.google.com
User-Agent: Go-http-client/1.1
Authorization: Bearer ya29..wwI10j5O2inB1xKuC8-fFiduHbDo4XW0tVOqZd-a6iiHgrdjCqS_DcwRu_g
Accept-Encoding: gzip
```
Response:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=UTF-8
P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
Date: Wed, 13 Apr 2016 00:37:20 GMT
Expires: Wed, 13 Apr 2016 00:37:20 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Content-Length: 165
Server: GSE
Set-Cookie: NID=78=fF5egC8I4Hvgh0WYv2zmKh53IoIrKwOAJXQMCsjOtfASsUdyfy6T3lMZFtVxG5p0HzV8xpINQyNDPmAdf-vE6OcjKDCBCFMz0hH7ZGNtukb9NSBeU7bw-Gdbp4_4rqyu;Domain=.google.com;Path=/;Expires=Thu, 13-Oct-2016 00:37:20 GMT;HttpOnly

<HTML>
<HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Internal Server Error</H1>
<H2>Error 500</H2>
</BODY>
</HTML>
```

**Comment by zipitup** [comment]
Just figured out a possible fix - I got it working.

The question where it asked for email to share with, it cannot be the same email you will be logging in to in your browser. In other words, you cannot be sharing the printer with yourself.

I never figured out a way to not enter an email, so I just entered another email I had, and then it worked!

**Comment by jacobmarble** [comment]
Please see my response in #206
