### ISSUE TITLE
Failed To Initialize Robot Account for googlegroups.com email

### ISSUE THREAD

**Issue by whizzzkid** [google/cups-connector#216]
issues #206 and #212 seem to be related but this is confusing.

Running "gcp-connector-util.exe init" will not accept following values in "User or group email address to share with:"

- Same email id from which you're logging in to add the printer
- any group email from googlegroups.com

however if use a temp gmail id to complete the json generation and then change the 'scope' in the generated json to the googlegroups.com email id, it seems to work.

The error here is with the server which always returns:
Failed to initialize robot account: 500 Internal Server Error

In case the email id does not meet the crieteria above.

**Comment by agoode** [comment]
That seems strange. I commented at #206. There may have been some transient backend errors. If they still occur, please comment at #206. I just renamed that issue to be more descriptive.
