### ISSUE TITLE
Needs to wait for cups on boot

### ISSUE THREAD

**Issue by helpdeskdan** [google/cups-connector#218]
After messing with init.d scripts, cursing and swearing, I've found nothing works but to put it in rc.local and after a good sleep 21 (or more).  Not that a more elegant solution isn't available, but my meager intelligence has not been able to produce it.  Backgrounding a trivial function with sleep should have worked, but doesn't seem to.  BTW, thanks for the excellent project.

**Comment by agoode** [comment]
Are you on Raspberry Pi? If so, make sure you are up to date (https://www.raspberrypi.org/documentation/raspbian/updating.md) and then follow the instructions again at https://github.com/google/cups-connector/wiki/Installing-on-Raspberry-Pi-Raspbian-Jessie.

Specifically, you want to use the systemd unit file:
https://github.com/google/cups-connector/wiki/Run-Connector-Automatically-on-Boot

I just updated the wiki page to explicitly wait for cups and avahi.

If my assumptions are wrong, please reopen this issue.

**Comment by helpdeskdan** [comment]
When I get a second, I'll try the new init script - thanks
