### ISSUE TITLE
Functionality questions and GCP Service for Windows?

### ISSUE THREAD

**Issue by leotohill** [google/cups-connector#219]
I know this is an Issues forum but I don't know where else to go with my questions.  Apologies in advance. 

1) On Windows, is there any functional difference between this project and GCP Service for WIndows, other than local printing?

2) Local printing looks great. Is it based on Privet?  Do I understand correctly that no google account is required in this usage?

Thanks. 

Leo Tohill

**Comment by jacobmarble** [comment]
Hi Leo-

1) This connector is probably more stable, and is beta quality on Windows.
I would like it to replace the GCP Service for Windows, but I'm very short
on time for it these days.

2) Yes, local printing is just Privet. No Google account is needed to use
it. Windows doesn't have Privet yet.

I always have time to review pull requests.

**Comment by leotohill** [comment]
Thanks for the response. In the local printing scenario, how does a client submit a print job?  Does it use privet discovery features to find the service?

**Comment by jacobmarble** [comment]
Yes. You can see a full-functioning Privet service in the CUPS connector,
just build this connector under Linux or OSX.

**Comment by agoode** [comment]
We do have a mailing list now, although we plan to rename it (see #241). Sorry we didn't have one before for you to ask your question.

I'll close this issue, please use the mailing list or open an issue if you need help.
