### ISSUE TITLE
cloudprint disconnects from admin.google.com

### ISSUE THREAD

**Issue by dmonty2** [google/cups-connector#221]
Our school district has about 50 sites and 450 printers shared up to google cloudprint using cups-connector.  This is working well.

https://admin.google.com is used to share those printers to labs of chromebooks.  The problem we are having is that admin.google.com gets disconnected from www.google.com/cloudprint and the chromebooks can't see any print shares or printers.  See attached screenshot.

![cloudprint_disconnect](https://cloud.githubusercontent.com/assets/1381071/15191996/10e32d0a-176c-11e6-866d-9dc4ba559fd0.png)

The printers that the chromebooks can not see/use are tagged as "Other printers" in the admin.google.com site.  However when i send a test job from www.google.com/cloudprint to the printer it works fine - so cloudprint is working but google chromebook connection to the cloud printers gets dropped/lost.

The only way to fix it is to log into admin.google.com device management then delete and re-add the printers.  This is getting a bit tedious deleting and re-adding the printers in the admin.google.com interface.

**Comment by jay0lee** [comment]
@dmonty2 : This doesn't sound related to cups-connector. It sounds like a Google admin console or GCP server issue. Have you filed a ticket with Google support?

**Comment by dmonty2** [comment]
cups-connector is probably not the issue as cloud-print continues to work even though chromebooks are broken.  Closing this ticket and will open a new ticket for Google Admin Console problem.

Thanks.
