### ISSUE TITLE
Local printer not showing up on laptop but on all other devices

### ISSUE THREAD

**Issue by apinnt** [google/cups-connector#227]
I have a printer hooked up and working using the cups-connector. The issue I'm having is it doesn't show up as a local destination on my laptop. It shows up on my phone, everyone elses phone in the house, and the tablets. 

I believe at one point it showed up on my laptop and worked. I had it setup as a cloud printer with my account but then decided to make it local only. My laptop had it connected as a cloud printer, I removed the entires in my browser for the cloud printer. I'm thinking this had something to do with it. Not sure though. I updated my chrome browser, didn't seem to effect it. 

Any ideas?

**Comment by apinnt** [comment]
I think I resolved it. Looks like I just restarted my laptop and it worked. Sorry about this. I restarted and cleared my cache on my chrome browser a hand full of times and I thought that would do it but apparently not. Just restarting my laptop solved it.

**Comment by agoode** [comment]
You might be seeing this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=593820

Star that chromium bug if it describes your issue, and thanks for filing a bug here.
