### ISSUE TITLE
Firewall issue

### ISSUE THREAD

**Issue by jfjm** [google/cups-connector#229]
Hi,

Is there a way to specify what port to e sued by cups-connector via the configuration file? I am running this on a machine that has firewall enabled, and with connector selecting a random port each time, it makes it difficult to automate startup process.

**Comment by agoode** [comment]
Do you mean the outgoing port, or the listening ports? Since aee65e86d4b6466bef1c31d56345f5986fb03c2d the software will select a port from the range 26000 to 26999. Each printer requires a port.

**Comment by agoode** [comment]
For outgoing ports, we could possibly add a config option to select the range.

**Comment by agoode** [comment]
There is a config option for the range, see `gcp-connector-util init -help` and look for `--local-port-low` and `--local-port-high`.

If this isn't the right answer to your issue, please reopen.

**Comment by jfjm** [comment]
I was referring to the listening ports, since that's the port the other devices need to connect to, and that's the port I need to open up for my firewall.

I did a gcp-connector-util init -help, and was not able to find --local-port-low or high option. I was not able to find that in the documentation on the wiki page as well. Are these ports for outgoing or listening ports?
