### ISSUE TITLE
README.md file needs improvement

### ISSUE THREAD

**Issue by KJS18** [google/cups-connector#41]
Although I eventually managed to get the CUPS connector working for a headless (text only) Ubuntu 14.04 LTS server, I was not able to do it by strictly following the README.md file. I had to do a fair amount of troubleshooting along the way. I have made a record of what I did available here:
https://drive.google.com/folderview?id=0B7SVWXy2l0CLfmlhVk8xb0Ricy11WlB4TVNqaUt3S1h0c3JVUGZud09MTDhvZnpMV3lseDQ&usp=sharing

**Comment by jacobmarble** [comment]
Hi KJS18! You clearly spent a lot of time on this, so thank you. I'll get around to integrating your feedback in a couple of days; in the meantime you're welcome to [submit a pull request](https://www.youtube.com/watch?v=81uKcXZoQ2A).

**Comment by KJS18** [comment]
I think a penny finally dropped somewhere. I just hope it's not a bad penny. The "go/bin/connector" path mentioned in README.md suggests to me that the author probably tested the CUPS connector using Windows but not Linux. I have updated/refined the content of everything at the above hyperlink accordingly.

**Comment by KJS18** [comment]
Hi Jacob! I have tidied the main document a little and updated my analysis (see readme_2nd.pdf).

**Comment by jacobmarble** [comment]
@KJS18 I have deleted most of the README, in favor of [the wiki](https://github.com/google/cups-connector/wiki). Also, releases now include binaries, which should help some of the confusion.

**Comment by miggs3** [comment]
I am a newbie, and I have read the documents in this thread, but I am having difficulty getting the CUPS connector loaded and functional.  I have a Ubuntu 14.04 CUPS server installed and I have shared printers out and they are accessible from an individual Google account, but that's it.  I want to use and share classic google cloud printers out to chromebooks without dedicating a computer to being logged into the Google printer account.  I've downloaded the binaries and created a client.conf file, but I receive the following error message:     
Google Cloud Print CUPS Connector version 2015.10.05-linux
no tool specified

I need cups-connector for dummies!  Is it something simple I am doing wrong?  Should I wait until the WIKI is updated further to try again?  Thanks for your help and let me know if I should wait for this tool get further along in development.

**Comment by jacobmarble** [comment]
> I have shared printers out and they are accessible from an individual Google account
What does that mean? Shared via Chrome or the CUPS Connector or ??

> I've downloaded the binaries and created a client.conf
You must have created `gcp-cups-connector.config.json` as described [here](https://github.com/google/cups-connector/wiki/Configuration), is that right?

When you run `gcp-cups-connector-util`, you're using a tool. Without a flag, it does nothing, hence the error. If you want to run the CUPS Connector, the command is `gcp-cups-connector`.

**Comment by miggs3** [comment]
Thank you for your prompt response!  I was able to share a printer via CUPS and print to it from Chrome.  You are correct, I did not generate my .json file.  I just did and the gcp-cups-connector is running with my printer account.  Looking at the instructions on the wiki for running at boot for rasberryPI, I will add similar instructions under /etc/init.d.  Is there better way?

**Comment by jacobmarble** [comment]
For a simple RPi setup, I usually recommend the last section here:
https://github.com/google/cups-connector/wiki/Install

**Comment by miggs3** [comment]
I added the code and rebooted my server, how do I determine if the cups-connector is running?  My GCP printers are showing up as offline.  I add the printers to my CUPS server, connect the printers to my printer google acount (chrome:\\devices) and then share printers in the Google console with my chromebooks.  It works when the computer I used to connect the printers to my google account is on, but once I shut my computer off, it seems like the GCP go off line.  I think I am missing a configuration step somewhere.  I want to share the classic printers on my CUPS server with my Google printers account and in turn my chromebooks.  Thanks again for your time.

**Comment by jacobmarble** [comment]
chrome://devices sets up the Chrome connector, which is builtin to Chrome. You'll need to undo that if you want to use the CUPS Connector.

After that, run `gcp-cups-connector` on the Pi, just to see if it works. I'm not sure you needed that config file; did you enable local or cloud or both when you ran `gcp-cups-connector-util -init`?

**Comment by miggs3** [comment]
I only enabled cloud when I ran gcp-cups-connector-util -init.  Do you think it would be cleaner for me to start over with a clean install?  Just so I understand, when I add network printers to my CUPS installation and then use my google printer account to 'authorize' the json file, all the printers on CUPS are available for me to use/share?  TIA

**Comment by jacobmarble** [comment]
No need for a clean install, I just need to know what's going on.

When you add or remove printers from the CUPS server, the CUPS Connector will automatically add or remove those printers from Cloud Print. So all of your CUPS printers are "synchronized" with Cloud Print.

You can manage sharing at google.com/cloudprint

**Comment by miggs3** [comment]
It's like magic :) Thank you for all your help, there is NO WAY I could have figured this out on my own.  The only thing I have left to figure out is how to automatically start the cups-connector when the Ubuntu server starts up.  Thanks again!

**Comment by miggs3** [comment]
I have noticed on the server that I am receiving a "17189 xmpp.go:114] XMPP conversation died" error, but it restarts.  The documents are printing, is this a normal informational error? Thanks!

**Comment by jacobmarble** [comment]
Glad to hear that things are working.

Yes, the XMPP error is normal, as long as it restarts. I should reduce the severity of that so that it doesn't log every time (it used to be a big problem, but the bug is fixed).

**Comment by jacobmarble** [comment]
I locked this conversation because it was resurrected for a different issue. If you're having a problem related to things discussed in this issue, please open a new issue (and feel free to reference this one).
