### ISSUE TITLE
Setting cups_job_full_username to true results in 2 jobs being created

### ISSUE THREAD

**Issue by roeften** [google/cups-connector#52]
A minor issue.

When setting cups_job_full_username to true, 2 identical jobs are created. One with the full username (i.e. email address) and one with the user part of the email address.

Not sure if this bug is a connector bug or a cloudprint bug.

**Comment by jacobmarble** [comment]
That is annoying. Definitely a connector bug.

**Comment by roeften** [comment]
Hello, sorry but that was my mistake. There is no bug, I accidentally run 2 instances each one with different configuration. Apologies.

**Comment by jacobmarble** [comment]
No problem. :-)
