### ISSUE TITLE
Support HTTP Proxy Servers

### ISSUE THREAD

**Issue by jay0lee** [google/cups-connector#58]
CUPS Connector should look for an honor the http_proxy and https_proxy variables when making HTTPS and XMPP connections.

**Comment by jacobmarble** [comment]
The connector talks to the GCP service via HTTPS, using a library that figures out HTTP Proxy without any help.

The connector talks to the XMPP service via TLS-encapsulated-TCP, using a library that doesn't know about HTTP, so doesn't know about HTTP proxies.

The solution is to encapsulate the XMPP conversation with HTTPS.

**Comment by jacobmarble** [comment]
Here's a thought. The XMPP conversation is TLS encapsulated, so the firewall doesn't know what's inside, and shouldn't prevent the connection because the protocol is XMPP.

So, the solution is *not* to encapsulate with HTTPS, but to simply honor HTTP(S)_PROXY like you said. Duh.
