### ISSUE TITLE
Document all connections cups-connector needs

### ISSUE THREAD

**Issue by jay0lee** [google/cups-connector#59]
To my knowledge, cups connector needs:
 - HTTPS port 443 connectivity to accounts.google.com (OAuth authorize and token refresh)
 - HTTPS port 443 connectivity to www.google.com (/cloudprint API endpoints)
 - XMPP port 443 connectivity to talk.google.com (print job notification channel)

in order to function correctly. No additional connections should be needed (assuming of course we have direct LAN connectivy to CUPS). We should confirm these are the only connections needed and document them accordingly.

**Comment by jay0lee** [comment]
For reference:

https://support.google.com/a/answer/3179170

(under the "Is Port 5222 required inbound for the print server?" collapsed area) says that the Chrome connector needs:

```
443 TCP (HTTPS), with connections to:
https://www.googleapis.com/*
https://accounts.google.com/*
https://www.google.com/cloudprint/*

5222 TCP (XMPP, using STARTTLS), with a persistent connection to:
talk.google.com
```
- The only reference to www.googleapis.com in the cups connector code is for the OAuth scope, that domain/URL should never be directly hit by cups connector.
- OOB, cups connector uses 443 for XMPP connection to talk.google.com

**Comment by jacobmarble** [comment]
The connector uses 443, not 5222, for XMPP. That's to help with restrictive firewalls.

**Comment by jacobmarble** [comment]
The connector can talk to printers via SNMP, to collect extra status info, like marker and paper levels. This isn't a firewall concern, since the printers probably live on the same subnet.

Local printing (Privet) uses mDNS to announce/discover, and plain-old-HTTP to communicate. This conversation is between client (CrBook, Android, iOS) and CUPS Connector, over the local subnet only.

**Comment by jacobmarble** [comment]
See the work in progress here:
https://github.com/google/cups-connector/wiki/What-is-Google-Cloud-Print%3F
