### ISSUE TITLE
undefined: strings.Compare

### ISSUE THREAD

**Issue by timmrogers** [google/cups-connector#67]
I'm getting an error when I try to install cups-connector on Debian 8. Am I missing a library or some other dependency perhaps? I appreciate any pointers. I'd love to get this working!

```
$ go get github.com/google/cups-connector/...
# github.com/google/cups-connector/lib
go/src/github.com/google/cups-connector/lib/deephash.go:50: undefined: strings.Compare
```
Thank you.

**Comment by jacobmarble** [comment]
I just tested this on Debian 8 amd64 using go1.5, no problem. I can't think of a reason this would happen off the top of my head.

Does this work? `go get github.com/golang/example/hello`

**Comment by timmrogers** [comment]
Yes, that worked fine. But I still get the error with cups-connector.

I am using the x86 version of Debian, if that matters. And I installed go
with apt-get.

Thanks for the reply.

**Comment by jacobmarble** [comment]
It looks like [jessie has Go 1.3.3](https://packages.debian.org/jessie/golang). AFAIK, the various repositories aren't worth using because they are so behind; this is a good example.

Go isn't hard to install from binaries. It's [one paragraph for Linux](https://golang.org/doc/install#install).

**Comment by jacobmarble** [comment]
OK, it's not one paragraph, but it's pretty short. :)

**Comment by timmrogers** [comment]
Thanks, Jacob.

As you guessed, the issue was with the old version of Go. It installs
nicely with Go1.5.1.

Now to see if I can get it configured!

**Comment by jacobmarble** [comment]
:-)

**Comment by Mike-Parker** [comment]
The following unofficial tarball for Go 1.5 on the Raspberrypi helped me with this problem and saved me having to build 1.5 from source:

http://denis.papathanasiou.org/posts/2015.08.30.post.html

**Comment by jacobmarble** [comment]
Thanks Mike. My idea for the future is to release binaries for RPi, save a lot of people some headache.

**Comment by Mike-Parker** [comment]
Hi Jacob,

After a rather rapid learning curve last weekend on compiling both Go and the connector from source on the Pi, binary releases would be greatly appreciated.

Thanks for all your hard work on the connector.

Best regards,

Mike
