### ISSUE TITLE
.../cups-connector/lib/deephash.go:50: undefined: strings.Compare

### ISSUE THREAD

**Issue by slegga** [google/cups-connector#73]
I got this error on raspberry pi 2 Raspbian Jessie and Kubuntu 15.04:
$ go get github.com/google/cups-connector/...
# github.com/google/cups-connector/lib
gopath/src/github.com/google/cups-connector/lib/deephash.go:50: undefined: strings.Compare
$ 
Is this a known bug or do I something wrong?

Best regards

**Comment by jacobmarble** [comment]
Hi, someone else just had the same problem. Please read #67 and let me know if that helps.

**Comment by jay0lee** [comment]
created pull request #74 to document min Go version needed for cups-connector.

@jacobmarble what would be awesome is if cups-connector could throw an error on "go get ..." if Go < 1.4 but I can't see any way to do that, can you?

**Comment by jacobmarble** [comment]
I just tried a [build constraint](http://godoc.org/go/build):
```
// +build go1.4
```
but that just make the relevant file, deephash.go, disappear:
```
$ go install
# github.com/google/cups-connector/manager
../manager/printermanager.go:187: undefined: lib.DeepHash
../manager/printermanager.go:191: undefined: lib.DeepHash
```

I'm getting closer to making binaries available for the next release. After that, we should see fewer of these issues.

**Comment by jacobmarble** [comment]
@slegga It takes hours to compile Go on a Raspberry Pi. If you don't make it, just wait a few days and I'll have a new release that will include binaries for Raspberry Pi.

**Comment by rrthomas** [comment]
I get this error yet I'm using go 1.4.2 as shipped with Ubuntu 14.04. Is 1.4 really recent enough?

**Comment by jay0lee** [comment]
AFAIK Ubuntu 14.04 shipped with Go 1.3. You can check your version with:

go version

It really is worth upgrading to the latest version of Go. I usually use GVM which makes it super simple on Ubuntu:

http://www.hostingadvice.com/how-to/install-golang-on-ubuntu/

```
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
gvm install go1.4.2
gvm use go1.4.2
export GOPATH_BOOTSTRAP=$GOPATH
gvm install go1.5.1
gvm use go1.5.1
```

**Comment by rrthomas** [comment]
$ go version
1.4.2

Turns out I've updated since the Trusty version, sorry for the confusion.

**Comment by jay0lee** [comment]
hmm... I can reproduce on 1.4.2. Sorry, I hadn't tried using 1.4.2 in awhile and the change that seems to have broke it is only a couple weeks old.

Quick fix for now would be to upgrade to Go 1.5.1.

@jacobmarble if we plan to continue Go 1.4.x support we'll need to figure out what's going on there.

**Comment by jacobmarble** [comment]
Hmm, looks like I shouldn't be using strings.Compare() anyhow:
https://golang.org/src/strings/compare.go

**Comment by jacobmarble** [comment]
I'm sorry that I dragged my feet on this simple fix.

**Comment by rrthomas** [comment]
Thanks for the fix; am I right in guessing I need to wait for a new release before the `go get` command in `README.md` will build the fixed version?

**Comment by jacobmarble** [comment]
No, go get will build the fixed version today.

Jacob

**Comment by rrthomas** [comment]
Thanks, turns out I needed `go get -u`.
