### ISSUE TITLE
https://www.google.com/cloudprint/list call failed: Storage timeout.

### ISSUE THREAD

**Issue by z** [google/cups-connector#76]
I'm trying to setup cups-connector on a Raspberry Pi v1.0B.

Port 443 is not blocked by my firewall and I'm running the latest version of golang (1.5.1) on raspbian 8.0 (jessie).

```
pi@raspberrypi ~ $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 4.1.6+ #810 PREEMPT Tue Aug 18 15:19:58 BST 2015 armv6l GNU/Linux
```
```
pi@raspberrypi ~ $ go version
go version go1.5.1 linux/arm
```

#### Local Config

I created a config for local-only with the following:

```
pi@raspberrypi ~ $ gocode/bin/connector-init 
Google Cloud Print CUPS Connector version DEV-linux
"Local printing" means that clients print directly to the connector via local subnet,
and that an Internet connection is neither necessary nor used.
Enable local printing?
y

"Cloud printing" means that clients can print from anywhere on the Internet,
and that printers must be explicitly shared with users.
Enable cloud printing?
n

The config file cups-connector.config.json is ready to rock.
```

Then I start the connector:

```
pi@raspberrypi ~ $ gocode/bin/connector
E0920 03:33:04.277863    2255 connector.go:33] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
E0920 03:33:04.738553    2255 connector.go:150] Ready to rock in local-only mode
Ready to rock in local-only mode
```

The printer shows up on `chrome://devices/` but when I try to register it, I receive the following error:

> ##### Could not complete registration
> An error has occured. Please check your printer and try again.

#### Cloud Print Config

If I create the config with the following options, enabling cloud print, I get the error stated in the topic.

(ids masked with xxx and ### respectively)

```
pi@raspberrypi ~ $ gocode/bin/connector-init 
Google Cloud Print CUPS Connector version DEV-linux
"Local printing" means that clients print directly to the connector via local subnet,
and that an Internet connection is neither necessary nor used.
Enable local printing?
y

"Cloud printing" means that clients can print from anywhere on the Internet,
and that printers must be explicitly shared with users.
Enable cloud printing?
y

Retain the user OAuth token to enable automatic sharing?
y        

User or group email address, or domain name, to share with:
xxx@gmail.com

Proxy name for this GCP CUPS Connector:
HP

Login to Google as the user that will own the printers, then visit this URL:

https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com&redirect_uri=oob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudprint&state=state

After authenticating, paste the provided code here:
##############################################

Acquired OAuth credentials for user account
Acquired OAuth credentials for robot account

The config file cups-connector.config.json is ready to rock.
Keep it somewhere safe, as it contains an OAuth refresh token.
```

I start it and within 30 seconds it crashes with the following error:

```
pi@raspberrypi ~ $ gocode/bin/connector
E0920 03:29:48.769721    2200 connector.go:33] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
F0920 03:30:11.771645    2200 connector.go:131] https://www.google.com/cloudprint/list call failed: Storage timeout.
goroutine 1 [running]:
github.com/golang/glog.stacks(0x54c200, 0x0, 0x0, 0x0)
	/home/pi/gocode/src/github.com/golang/glog/glog.go:769 +0xc4
github.com/golang/glog.(*loggingT).output(0x538970, 0x3, 0x965445a0, 0x51028e, 0xc, 0x83, 0x0)
	/home/pi/gocode/src/github.com/golang/glog/glog.go:720 +0x28c
github.com/golang/glog.(*loggingT).printDepth(0x538970, 0x3, 0x1, 0x965d1db8, 0x1, 0x1)
	/home/pi/gocode/src/github.com/golang/glog/glog.go:646 +0x1b0
github.com/golang/glog.(*loggingT).print(0x538970, 0x3, 0x965d1db8, 0x1, 0x1)
	/home/pi/gocode/src/github.com/golang/glog/glog.go:637 +0x44
github.com/golang/glog.Fatal(0x965d1db8, 0x1, 0x1)
	/home/pi/gocode/src/github.com/golang/glog/glog.go:1128 +0x3c
main.main()
	/home/pi/gocode/src/github.com/google/cups-connector/connector/connector.go:131 +0x102c
```

I'm not sure where I'm going wrong or misunderstanding the configuration. Any help is appreciated.

**Comment by jacobmarble** [comment]
Looks more like 1 second than 30 seconds.

"Storage timeout" is a GCP backend error. If this is happening a lot, then please notify me; it should only happen on rare occasion.

The CUPS Connector doesn't require registration.
- Printers are registered automatically as they are added to the CUPS server that the CUPS Connector is communicating with.
- Local printers don't require registration. Chrome(OS) should show them in the print dialog whenever the device is on the same subnet.

**Comment by jacobmarble** [comment]
BTW, thanks for the verbose report.

**Comment by z** [comment]
Thanks for getting back to me so quickly @jacobmarble, I didn't realize local printers don't require registration. I have verified I can print locally with cups-connector from a chromebook.

I do get "Storage timeout" every time using the Cloud Print Config above.

Let me know if I can provide any more information to help you troubleshoot.

**Comment by jacobmarble** [comment]
TODO: Talk to GCP backend engineers on Monday, about "Storage timeout".

**Comment by jacobmarble** [comment]
@z how many printers does the CUPS server have installed?

**Comment by jacobmarble** [comment]
@z Actually, two numbers. How many printers on that one proxy (CUPS server + CUPS connector), and also, how many Cloud Print printers does the user have in total?

Thanks

**Comment by z** [comment]
@jacobmarble There is only one printer.
One printer configured on the proxy and the same (one) printer in Cloud Print.

**Comment by jacobmarble** [comment]
What is the proxy name? It's possible that many people have chosen the same proxy name, and that the Cloud Print service isn't handling that very well.

**Comment by z** [comment]
I can try another name, I was using "HP" which I thought would be limited to my home network or google account.

**Comment by z** [comment]
@jacobmarble okay, I just tried the name "asdklfjasdlfjaslkdfjdsalksdfjasdfasdfas" with the Cloud Print config and it does not crash like it does when I use "HP" as the proxy name. Seems you've hit the nail on the head.

**Comment by jacobmarble** [comment]
Good to know. Here's some context:
https://groups.google.com/forum/#!topic/gcp-developers/-WTeE1wlLDs

**Comment by jacobmarble** [comment]
@z May I ask, why did you choose "HP"?

**Comment by z** [comment]
@jacobmarble I thought the proxy name was limited to my account. The raspberry pi was meant to only be used as a way for my mother to print from the "classic" HP printer from her Chromebook.

**Comment by jacobmarble** [comment]
The name is limited to your account, but it's stored in a database with millions of other proxy names, so funny things happen when a common name is chosen.

It's our (Cloud Print team) fault, and it will be fixed in a couple of weeks. I'm glad that we resolved your situation. :-)

**Comment by z** [comment]
Thanks for your help, I saw the note in the google groups link above :)
