### ISSUE TITLE
README.md is not the place to give a tutorial on building from source

### ISSUE THREAD

**Issue by rrthomas** [google/cups-connector#78]
It's nice to give a few system-specific non-Go build dependency lists, e.g. yum/apt/brew commands for Fedora/RHEL, Debian/Ubuntu, but explaining how to install XCode is out of scope. Adding detailed instructions simply imposes a maintenance burden. This stuff is easy to find.

One of the joys of go is that `go get` is so simple, so just document the build deps (minimum version of Go and CUPS, required libraries) and then get on with the project-specific stuff. Even better, put it in scripts so it's right: does Go not have an equivalent of GNU autotools' ability to look for build deps and tell the user what's missing?

**Comment by jacobmarble** [comment]
On your first point, I agree. I started the wiki recently, plan to clean up README.md soon.

Secondly, `go get` does, indeed, fetch dependencies on it's own. Things aren't so tidy when you need a C library, however. Hence the stone-aged "here's what to do with distro X". If you want to work on a script to handle this stuff, then be my guest. I don't think Go lends itself well to this, however.

I keep saying this: binaries are coming. Before Friday, I hope. You say "This stuff is easy to find." and for programmers, you're right. For the rest of the world, binaries resolve the need to explain so many details.

**Comment by jacobmarble** [comment]
https://github.com/google/cups-connector/wiki
