### ISSUE TITLE
Use standard location for default config file

### ISSUE THREAD

**Issue by rrthomas** [google/cups-connector#79]
On anything but OS X that would be under $XDG_CONFIG_HOME (or its default value). (Or does Go have a way to get this location in a portable way?) Either way, storing the information in a standard location avoids needing either to run the programs in a particular directory or always to pass the config file's location.

**Comment by jacobmarble** [comment]
Thanks, I'll look up $XDG_CONFIG_HOME

**Comment by rrthomas** [comment]
Jolly good, thanks!
