### ISSUE TITLE
oauth2 failure

### ISSUE THREAD

**Issue by rrthomas** [google/cups-connector#81]
I get the following error:

```
$ connector-util -config-filename ~/.config/cups-connector.config.json -show-gcp-printer-status -printer-id bunyan
Google Cloud Print CUPS Connector version DEV-linux
F0920 14:08:40.664864   29142 connector-util.go:410] POST failure: Post https://www.google.com/cloudprint/printer: oauth2: token expired and refresh token is not set
```

I can't find anything about this in the documentation, and a quick search throws up only hints for developers writing similar code to this, and of options pertaining to OAuth in other Google Cloud Print connectors (but not this one). Sorry if I missed something, but otherwise, any suggestions?

**Comment by jay0lee** [comment]
The printer id should be a random-looking set of chars, not the name. I plan to add a list printers function but for now browse to the printer at google.com/cloudprint and look at the advanced details.

OAuth error seems odd. In your config file is robot_refresh_token set? (Don't post the value publicly)

Jay

**Comment by jay0lee** [comment]
Wiki docs are coming soon on these commands, they just got added last week. We need a "Under Construction" sign :-) But Jacob is doing awesome things and moving very fast.

**Comment by jay0lee** [comment]
Hmmm. Not sure connector-util even takes -config-filename argument. It may currently just look in cwd. That obviously would need a fix but see if being in the same directory as the config file when running connector-util makes a difference.

**Comment by jacobmarble** [comment]
TODO: Look at `connector-util -config-filename` when back at work on Monday.

**Comment by rrthomas** [comment]
`connector-util -help` lists `-config-filename` as an option, certainly.

Nothing about `refresh` is listed in my config file. I just used the default output of `connector-init`, answering `y` for local use and `n` for remote.

I can't see how to list printer IDs, so no idea how to ask about a printer; sorry, I had assumed these were CUPS print queue names. Hence I can't tell whether being in the same directory as my config file helps.

`connector-monitor` says `cups-printers=1` (which is right for my system) but `gcp-printers=0`; does that mean that somehow my printer hasn't been set up by connector?

Sorry to be clueless, I browsed the wiki, which doesn't say much, and the README gives the impression that this should all basically just work.

**Comment by jay0lee** [comment]
Ah, OK. So if you are only using local, no cloud then you have no GCP printers and no OAuth tokens. Queue/job management should be done in CUPS for local printers.

TODO for jayhlee: detect local-only configs and let connector-util handle gracefully.

**Comment by rrthomas** [comment]
My understanding was that "local" means "local subnet". If I run Google Cloud Print on my Android phone, it can't see any printers.

**Comment by jay0lee** [comment]
Jacob may know better but AFAIK, Chrome browser/OS are the only GCP clients which support local printing. If you need to print from Android reconfigure with cloud=yes.

**Comment by rrthomas** [comment]
Thanks very much for the help. So, I reconfigured with cloud on, authorized the app etc. Now my phone still stolidly says "No printers to add".

**Comment by jay0lee** [comment]
Make sure:

https://play.google.com/store/apps/details?id=com.google.android.apps.cloudprint

Is installed. Shouldn't need to register/add on Android. Just teyvti print something.

**Comment by rrthomas** [comment]
Yes, I have that installed, that's where I'm trying to add a printer. It says "No printers to add". I don't know how I would "just try to print something", but from reading I wonder if that requires Android 4.4; I have 4.2. However, if I choose a file to print from within the app, that seems to work, thanks very much!

**Comment by jacobmarble** [comment]
I emailed the SWE responsible for the Android GCP client yesterday because I ran into the same issue.

**Comment by jacobmarble** [comment]
TODO: Add local-printers to monitor output

Jacob

**Comment by jacobmarble** [comment]
- The Android client will get an update in a month or so, which will add local printer support.
- No need to "add" a local printer GCP clients. When you're on the same subnet, it appears in your print dialog. When you leave the subnet, it disappears from the dialog.
- Same goes for "registering" new printers. The connector registers, updates and un-registers printers as they change in CUPS.
- Working on monitor.

**Comment by rrthomas** [comment]
Thanks very much for the update.

**Comment by jay0lee** [comment]
Hi rrthomas, do you still have open questions on this issue or can we close this out?

**Comment by rrthomas** [comment]
Do close it, thanks!

-- 
http://rrt.sc3d.org
