### ISSUE TITLE
Support PPD keyword KMDuplex

### ISSUE THREAD

**Issue by jacobmarble** [google/cups-connector#88]
Jobs via connector always print duplex on some Konica Minolta printers. This might be an easy fix by parsing CUPS `sides` attribute.

```
*OpenUI  *KMDuplex/Print Type: PickOne
*OrderDependency: 5 AnySetup *KMDuplex
*DefaultKMDuplex: Double
*KMDuplex Single/1-Sided:  "<< /Duplex false >> setpagedevice
 << /Layout 0 >> /KMOptions /ProcSet findresource /setKMoptions get exec"
*End
*KMDuplex Double/2-Sided:  "<< /Duplex true >> setpagedevice
 << /Layout 0 >> /KMOptions /ProcSet findresource /setKMoptions get exec"
*End
*KMDuplex Booklet/Booklet:  "<< /Duplex true >> setpagedevice
 << /Layout 1 >> /KMOptions /ProcSet findresource /setKMoptions get exec"
*End
*CloseUI: *KMDuplex
```

**Comment by jacobmarble** [comment]
This is not fixed. The PPD is parsed correctly, but the ticket is not. I'm yet not sure which is the correct way to fix this.

**Comment by jacobmarble** [comment]
@charlie2alpha if you have a moment, verify that duplexing is broken on your printer. This patch should fix it.

**Comment by charlie2alpha** [comment]
Oh, I tried the patch just this morning actually, I did manage to print in both sides of the paper. Last time I tried it, some time last week, that didn't work. Seems to work for me.

**Comment by jacobmarble** [comment]
Neat-o, thanks!
