### ISSUE TITLE
"connector.go daemon not running" when in docker container

### ISSUE THREAD

**Issue by hubertbanas** [google/cups-connector#90]
After running "Google Cloud Print CUPS Connector" in Debian VM for some time I decided to try it out in docker container. 

I was able to have "go" installed as well as gcp compiled. I was also able to use connector-init and I got cups-connector.config.json

I confirmed that the newly created cups-connector.config.json consist the following entry:

```bash 
"monitor_socket_filename": "/tmp/cups-connector-monitor.sock",
```

Unfortunately when trying to start connector I'm getting the following:

```bash
root@ffb6ce0f60dc:/tmp# /opt/gcp_cups_connector/connector -config-filename /config/cups-connector.config.json
E0924 11:03:11.645324     217 connector.go:33] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
F0924 11:03:12.324227     217 connector.go:122] Daemon not running
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc96100, 0x0, 0x0, 0x0)
        /tmp/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xc71bc0, 0xc800000003, 0xc8200f20c0, 0xa5172d, 0xc, 0x7a, 0x0)
        /tmp/src/github.com/golang/glog/glog.go:720 +0x2b8
github.com/golang/glog.(*loggingT).printDepth(0xc71bc0, 0x3, 0x1, 0xc820237df0, 0x1, 0x1)
        /tmp/src/github.com/golang/glog/glog.go:646 +0x1b8
github.com/golang/glog.(*loggingT).print(0xc71bc0, 0x3, 0xc820237df0, 0x1, 0x1)
        /tmp/src/github.com/golang/glog/glog.go:637 +0x50
github.com/golang/glog.Fatal(0xc820237df0, 0x1, 0x1)
        /tmp/src/github.com/golang/glog/glog.go:1128 +0x49
main.main()
        /tmp/src/github.com/google/cups-connector/connector/connector.go:122 +0x12c7
```

I would appreciate any suggestions to get this going in docker. 

I will be more then happy to provide any debug needed such as connector.ERROR, connector.FATAL
connector.INFO, connector.WARNING, etc.

Thanks
Hubert

**Comment by jacobmarble** [comment]
Pull request #86 will make the error clearer. "Daemon not running" would, in that case, be "Failed to start Avahi client: Daemon not running", which means that the Avahi daemon needs to be started.

**Comment by hubertbanas** [comment]
Thanks for the info. Connector no longer complains after I added avahi to the container.

**Comment by jacobmarble** [comment]
Any time :)

Jacob

**Comment by smithkyle** [comment]
I'm struggling with this in an alpine docker image. I have added avahi via apk, and compiled gcp without errors, but even after starting `avahi-daemon -D` the gcp-cups-connector still shows `Failed to start Avahi client: Daemon not running`, even though I can verify that it is, indeed running.

What did you do to get it to work in docker? Or how can I further debug the avahi daemon?
