### ISSUE TITLE
Feature request: multiple cups-conectors for one domain.

### ISSUE THREAD

**Issue by dmonty2** [google/cups-connector#98]
Our district has:
* a cups server at each of our 50 schools.
* one google admin domain - for assigning cloud-print printers to chromebooks by school.

Request:
1) ability to prefix each cups-connector printer instance with a "site" name. e.g.
- nkss-library
- skss-library
- aberdeen-library

2) ability to white-list which printers are shared by cups-connector.
- e.g. allow "library" printer & deny "principal" printer.

Thanks.

**Comment by jay0lee** [comment]
re #1: @jacobmarble how do you feel about adding the following config options:
* gcp_printer_prefix
* gcp_printer_postfix
* local_printer_prefix
* local_printer_postfix

defaults would be blank in all cases.

re: #2 @dmonty2 I plan to add arguments to gcp-cups-connector-util that allow sharing individual printers with users groups. So you'd be able to run something like:

gcp-cups-connector-util --printer-id <id of student printer> --share students@school.edu

Do these proposed changes meet your needs?

**Comment by jacobmarble** [comment]
@dmonty2 How many printers are at each site? Max, min, rough average? This is mostly to satisfy my curiosity; lots of customers have similar situations, and we've been trying to find a general solution.

@jay0lee Proxy names should cover this use case. There is a CUPS server at each school, so there is a connector at each school, so there is a proxy name associated with each school. You can query all printers belonging to a proxy with the /list API, then share/unshare.

**Comment by dmonty2** [comment]
Answers to the above questions...

465 printers registered in our district - average 9-10 printers per school.  The other reason for feature #2 ( white-list printers ) is so that I do not import all 465 printers into cloudprint & google domain as the Cromebooks usually only need access to two or three printers from each school.

*_prefix and *_postfix ideas sound good.

Currently I'm using a modified version of armooo/cloudprint but it would be nice to use the official google cups-connector.

**Comment by jacobmarble** [comment]
Ah, you don't want to share all of the CUPS server's printers with GCP? That's interesting, and I'm sorry I misunderstood.

Adding a whitelist to the config file is doable. I'm not going to add postfix/prefix logic, but how about if the whitelist can be a regular expression? That way, you decide on a naming scheme that works for you, and someone else can do something else.

Consider also that CUPS printers have two attributes (key/value pairs) that can be manipulated by the user: printer-info and printer-location. We could talk about filtering on either of those.

**Comment by dmonty2** [comment]
After working through admin.google.com -  just import all cups printers into the cloud and use the admin interface to assign which printers to chromebook groups.  Drop the #2 whitelist idea. just the ability to prefix the cloudprint printer with site name.

**Comment by jacobmarble** [comment]
After a conversation with @dmonty2, it's clear that whitelisting CUPS printers wouldn't be as effective as better sharing capabilities.

@jay0lee the --share flag assumes that user_oauth_token is present in the config file, yes? That might be a problem because the -init flag assumes that the user said "yes" to automatic sharing. Might need to adjust that, but it can be worked around.

Also, the web interface can be used to share printers. It would be nice to make that easier some day.

**Comment by jacobmarble** [comment]
@dmonty2 how does the prefix help at this point? To quickly associate a printer with a school when managing them at admin.google.com?

@jay0lee if that's so then we should see about exposing the proxy name to the web interface.

**Comment by dmonty2** [comment]
The prefix helps - click a organization group in admin.google.com  => Cloud Print => Manage.  search for the "prefix" name and it shows all the printers for that school/site.

Also in www.google.com/cloudprint - just search for the prefix so see all the printers for that school.

**Comment by adam-pendles** [comment]
In https://www.google.com/cloudprint#printers
<http://www.google.com/cloudprint>, could you search by proxy name (which
is already exposed in the web view - expand the 'Advanced Details' for a
printer)?  I don't have a domain to test with in admin.google.com, but
likewise could you instead use the proxy name for your query?

On Wed, 30 Sep 2015 at 08:56 Dean Montgomery <notifications@github.com>
wrote:

> The prefix helps - click a organization group in admin.google.com =>
> Cloud Print => Manage. search for the "prefix" name and it shows all the
> printers for that school/site.
>
> Also in www.google.com/cloudprint - just search for the prefix so see all
> the printers for that school.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cups-connector/issues/98#issuecomment-144214731>
> .
>
-- 

Adam Pendlebury | Corporate Operations Engineer | apendlebury@google.com | +61
424 072 303

**Comment by jay0lee** [comment]
Here's what the admin.google.com dialog looks like. The filter seems to only search on printer name, not proxy.

@dmonty2: might the simplest option be to name the CUPS printers by school? e.g:

sunnyside-admin-laser1
stonebrook-students-laser1

etc? We can still explore the prefix / suffix options but just looking for the simplest solution here.

**Comment by dmonty2** [comment]
I've noticed that www.google.com/cloudprint will hang for a minute or so when I make changes to printers.    Screenshot shows wheel spinning below.   There are 115 printers attached to the user account, will this lag get worse if all 465 printers are shared out?


![cloudprint_hang](https://cloud.githubusercontent.com/assets/1381071/10197973/cc804af8-674e-11e5-9185-abb4eebf22df.png)

**Comment by dmonty2** [comment]
@jay0lee the cups/samba print queues were named to make it easy for students/staff.  Changing the cups print queues to include school name will break windows/samba print queue mappings.
  \\server\library                       queue will have to be remapped to:
  \\server\darkvalley-library

Renaming queues is not a good/easy solution.

**Comment by jacobmarble** [comment]
@dmonty2 it doesn't get much slower than what you're experiencing as more printers are added (tested with over 1000 printers).

Looking into the prefix idea.

**Comment by jacobmarble** [comment]
@dmonty2 when you try the connector, follow the wiki instructions to initialize a config file, then edit the config file and look for the `display_name_prefix` value. Set it to something like "darkvalley-" and this will create a GCP printer named "darkvalley-library" assuming there is a printer called "library".

I'll let you close this bug when you're satisfied.

**Comment by dmonty2** [comment]
Thank you.  I'll test it later today.

**Comment by jacobmarble** [comment]
@dmonty2 any update?

**Comment by dmonty2** [comment]
The new cups-connector codebase with prifix is installed and working in a few of our schools.  So far there have been no issues.  Thanks for the patch.

**Comment by jacobmarble** [comment]
I'm glad.
